project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - a-level/23-chemical-energetics.qmd
    - a-level/24-electrochemistry.qmd
    - a-level/25-equilibria.qmd
    - a-level/26-reaction-kinetics.qmd
    - a-level/27-group-2.qmd
    - a-level/28-transition-elements.qmd
    - a-level/29-organic-chemistry.qmd
    - a-level/30-hydrocarbons.qmd
    - a-level/31-halogen-compounds.qmd

website:
  title: "CIE Chemistry 9701"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: 学习首页
      - section: "A Level"
        contents:
          - href: a-level/23-chemical-energetics.qmd
            text: "23 Chemical energetics"
          - href: a-level/24-electrochemistry.qmd
            text: "24 Electrochemistry"
          - href: a-level/25-equilibria.qmd
            text: "25 Equilibria"
          - href: a-level/26-reaction-kinetics.qmd
            text: "26 Reaction kinetics"
          - href: a-level/27-group-2.qmd
            text: "27 Group 2"
          - href: a-level/28-transition-elements.qmd
            text: "28 Chemistry of transition elements"
          - href: a-level/29-organic-chemistry.qmd
            text: "29 An introduction to A Level organic chemistry"
          - href: a-level/30-hydrocarbons.qmd
            text: "30 Hydrocarbons"
          - href: a-level/31-halogen-compounds.qmd
            text: "31 Halogen compounds"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    smooth-scroll: true
    css: styles.css
    include-after-body: scripts/progress.html

lang: zh
