project:
  type: website
  output-dir: _site
  render:
    - a-level/1-atomic-structure.qmd
    - a-level/2-atoms-molecules-stoichiometry.qmd
    - a-level/3-chemical-bonding.qmd
    - a-level/4-states-of-matter.qmd

website:
  title: "CIE Chemistry 9701"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.html
        text: 学习首页
      - section: "AS Level"
        contents:
          - href: a-level/1-atomic-structure.html
            text: "1 Atomic structure"
          - href: a-level/2-atoms-molecules-stoichiometry.html
            text: "2 Atoms, molecules and stoichiometry"
          - href: a-level/3-chemical-bonding.html
            text: "3 Chemical bonding"
          - href: a-level/4-states-of-matter.html
            text: "4 States of matter"
      - section: "A Level"
        contents:
          - href: a-level/23-chemical-energetics.html
            text: "23 Chemical energetics"
          - href: a-level/24-electrochemistry.html
            text: "24 Electrochemistry"
          - href: a-level/25-equilibria.html
            text: "25 Equilibria"
          - href: a-level/26-reaction-kinetics.html
            text: "26 Reaction kinetics"
          - href: a-level/27-group-2.html
            text: "27 Group 2"
          - href: a-level/28-transition-elements.html
            text: "28 Chemistry of transition elements"
          - href: a-level/29-organic-chemistry.html
            text: "29 An introduction to A Level organic chemistry"
          - href: a-level/30-hydrocarbons.html
            text: "30 Hydrocarbons"
          - href: a-level/31-halogen-compounds.html
            text: "31 Halogen compounds"
          - href: a-level/32-hydroxy-compounds.html
            text: "32 Hydroxy compounds"
          - href: a-level/33-carboxylic-acids-and-derivatives.html
            text: "33 Carboxylic acids and derivatives"
          - href: a-level/34-nitrogen-compounds.html
            text: "34 Nitrogen compounds"
          - href: a-level/35-polymerisation.html
            text: "35 Polymerisation"
          - href: a-level/36-organic-synthesis.html
            text: "36 Organic synthesis"
          - href: a-level/37-analytical-techniques.html
            text: "37 Analytical techniques"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    smooth-scroll: true
    css: styles.css
    include-after-body: scripts/progress.html

lang: zh
