<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-Hans" xml:lang="zh-Hans"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>23 Chemical energetics – CIE Chemistry 9701</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../a-level/24-electrochemistry.html" rel="next">
<link href="../a-level/13-introduction-to-as-organic-chemistry.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a2a938b4dd5711f7a799c87bd16ba44c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../a-level/23-chemical-energetics.html">A Level</a></li><li class="breadcrumb-item"><a href="../a-level/23-chemical-energetics.html">23 Chemical energetics</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="搜索" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">CIE Chemistry 9701</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="搜索"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">学习首页</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">AS Level</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/1-atomic-structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1 Atomic structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/2-atoms-molecules-stoichiometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2 Atoms, molecules and stoichiometry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/3-chemical-bonding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3 Chemical bonding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/4-states-of-matter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4 States of matter</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/5-chemical-energetics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5 Chemical energetics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/6-electrochemistry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6 Electrochemistry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/7-equilibria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7 Equilibria</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/8-reaction-kinetics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8 Reaction kinetics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/9-periodic-table-chemical-periodicity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9 The Periodic Table: chemical periodicity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/10-group-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10 Group 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/11-group-17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11 Group 17</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/12-nitrogen-and-sulfur.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12 Nitrogen and sulfur</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/13-introduction-to-as-organic-chemistry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13 An introduction to AS Level organic chemistry</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">A Level</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/23-chemical-energetics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">23 Chemical energetics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/24-electrochemistry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">24 Electrochemistry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/25-equilibria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">25 Equilibria</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/26-reaction-kinetics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">26 Reaction kinetics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/27-group-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">27 Group 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/28-transition-elements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">28 Chemistry of transition elements</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/29-organic-chemistry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">29 An introduction to A Level organic chemistry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/30-hydrocarbons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">30 Hydrocarbons</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/31-halogen-compounds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">31 Halogen compounds</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/32-hydroxy-compounds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">32 Hydroxy compounds</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/33-carboxylic-acids-and-derivatives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">33 Carboxylic acids and derivatives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/34-nitrogen-compounds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">34 Nitrogen compounds</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/35-polymerisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">35 Polymerisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/36-organic-synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">36 Organic synthesis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../a-level/37-analytical-techniques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">37 Analytical techniques</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">该页面内容</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#lattice-energy-and-bornhaber-cycles" id="toc-lattice-energy-and-bornhaber-cycles" class="nav-link" data-scroll-target="#lattice-energy-and-bornhaber-cycles">23.1 Lattice energy and Born–Haber cycles</a>
  <ul class="collapse">
  <li><a href="#enthalpy-change-of-atomisation原子化焓变" id="toc-enthalpy-change-of-atomisation原子化焓变" class="nav-link" data-scroll-target="#enthalpy-change-of-atomisation原子化焓变">Enthalpy change of atomisation（原子化焓变）</a></li>
  <li><a href="#lattice-energy晶格能-晶格焓" id="toc-lattice-energy晶格能-晶格焓" class="nav-link" data-scroll-target="#lattice-energy晶格能-晶格焓">Lattice energy（晶格能 / 晶格焓）</a></li>
  <li><a href="#electron-affinity电子亲和能" id="toc-electron-affinity电子亲和能" class="nav-link" data-scroll-target="#electron-affinity电子亲和能">Electron affinity（电子亲和能）</a></li>
  <li><a href="#影响电子亲和能的因素" id="toc-影响电子亲和能的因素" class="nav-link" data-scroll-target="#影响电子亲和能的因素">影响电子亲和能的因素</a></li>
  <li><a href="#bornhaber-cyclesbornhaber-循环" id="toc-bornhaber-cyclesbornhaber-循环" class="nav-link" data-scroll-target="#bornhaber-cyclesbornhaber-循环">Born–Haber cycles（Born–Haber 循环）</a></li>
  <li><a href="#calculations-using-bornhaber-cyclesbornhaber-循环计算" id="toc-calculations-using-bornhaber-cyclesbornhaber-循环计算" class="nav-link" data-scroll-target="#calculations-using-bornhaber-cyclesbornhaber-循环计算">Calculations using Born–Haber cycles（Born–Haber 循环计算）</a></li>
  <li><a href="#影响晶格能的因素离子电荷与离子半径" id="toc-影响晶格能的因素离子电荷与离子半径" class="nav-link" data-scroll-target="#影响晶格能的因素离子电荷与离子半径">影响晶格能的因素：离子电荷与离子半径</a></li>
  </ul></li>
  <li><a href="#enthalpies-of-solution-and-hydration" id="toc-enthalpies-of-solution-and-hydration" class="nav-link" data-scroll-target="#enthalpies-of-solution-and-hydration">23.2 Enthalpies of solution and hydration</a>
  <ul class="collapse">
  <li><a href="#enthalpy-change-of-solution溶解焓变" id="toc-enthalpy-change-of-solution溶解焓变" class="nav-link" data-scroll-target="#enthalpy-change-of-solution溶解焓变">Enthalpy change of solution（溶解焓变）</a></li>
  <li><a href="#enthalpy-change-of-hydration水合焓变" id="toc-enthalpy-change-of-hydration水合焓变" class="nav-link" data-scroll-target="#enthalpy-change-of-hydration水合焓变">Enthalpy change of hydration（水合焓变）</a></li>
  <li><a href="#溶解焓与水合焓的能量循环" id="toc-溶解焓与水合焓的能量循环" class="nav-link" data-scroll-target="#溶解焓与水合焓的能量循环">溶解焓与水合焓的能量循环</a></li>
  <li><a href="#影响水合焓的因素" id="toc-影响水合焓的因素" class="nav-link" data-scroll-target="#影响水合焓的因素">影响水合焓的因素</a></li>
  </ul></li>
  <li><a href="#entropy-change" id="toc-entropy-change" class="nav-link" data-scroll-target="#entropy-change">23.3 Entropy change</a>
  <ul class="collapse">
  <li><a href="#entropy熵" id="toc-entropy熵" class="nav-link" data-scroll-target="#entropy熵">Entropy（熵）</a></li>
  <li><a href="#标准熵变计算" id="toc-标准熵变计算" class="nav-link" data-scroll-target="#标准熵变计算">标准熵变计算</a></li>
  </ul></li>
  <li><a href="#gibbs-free-energy-change" id="toc-gibbs-free-energy-change" class="nav-link" data-scroll-target="#gibbs-free-energy-change">23.4 Gibbs free energy change</a>
  <ul class="collapse">
  <li><a href="#the-gibbs-equationgibbs-方程" id="toc-the-gibbs-equationgibbs-方程" class="nav-link" data-scroll-target="#the-gibbs-equationgibbs-方程">The Gibbs equation（Gibbs 方程）</a></li>
  <li><a href="#reaction-feasibility反应可行性" id="toc-reaction-feasibility反应可行性" class="nav-link" data-scroll-target="#reaction-feasibility反应可行性">Reaction feasibility（反应可行性）</a></li>
  </ul></li>
  <li><a href="#structured-questions" id="toc-structured-questions" class="nav-link" data-scroll-target="#structured-questions">Structured Questions</a>
  <ul class="collapse">
  <li><a href="#chemical-energetics---easy" id="toc-chemical-energetics---easy" class="nav-link" data-scroll-target="#chemical-energetics---easy">5.1 Chemical Energetics - Easy</a></li>
  <li><a href="#example-1-lattice-energy-and-the-cao-bornhaber-cycle-5.1-sq-easy-q1" id="toc-example-1-lattice-energy-and-the-cao-bornhaber-cycle-5.1-sq-easy-q1" class="nav-link" data-scroll-target="#example-1-lattice-energy-and-the-cao-bornhaber-cycle-5.1-sq-easy-q1">Example 1 · Lattice energy and the CaO Born–Haber cycle · 5.1 SQ Easy Q1</a></li>
  <li><a href="#example-2-potassium-fluoride-cycle-and-enthalpy-of-solution-5.1-sq-easy-q2" id="toc-example-2-potassium-fluoride-cycle-and-enthalpy-of-solution-5.1-sq-easy-q2" class="nav-link" data-scroll-target="#example-2-potassium-fluoride-cycle-and-enthalpy-of-solution-5.1-sq-easy-q2">Example 2 · Potassium fluoride cycle and enthalpy of solution · 5.1 SQ Easy Q2</a></li>
  <li><a href="#example-3-nacl-lattice-enthalpy-electron-affinity-and-the-arrows-for-oxygen-5.1-sq-easy-q3" id="toc-example-3-nacl-lattice-enthalpy-electron-affinity-and-the-arrows-for-oxygen-5.1-sq-easy-q3" class="nav-link" data-scroll-target="#example-3-nacl-lattice-enthalpy-electron-affinity-and-the-arrows-for-oxygen-5.1-sq-easy-q3">Example 3 · NaCl lattice enthalpy, electron affinity and the arrows for oxygen · 5.1 SQ Easy Q3</a></li>
  <li><a href="#chemical-energetics---medium" id="toc-chemical-energetics---medium" class="nav-link" data-scroll-target="#chemical-energetics---medium">5.1 Chemical Energetics - Medium</a></li>
  <li><a href="#example-4-lattice-energy-of-potassium-oxide-5.1-sq-medium-q1" id="toc-example-4-lattice-energy-of-potassium-oxide-5.1-sq-medium-q1" class="nav-link" data-scroll-target="#example-4-lattice-energy-of-potassium-oxide-5.1-sq-medium-q1">Example 4 · Lattice energy of potassium oxide · 5.1 SQ Medium Q1</a></li>
  <li><a href="#example-5-lithium-fluoride-bornhaber-cycle-and-solution-enthalpies-5.1-sq-medium-q2" id="toc-example-5-lithium-fluoride-bornhaber-cycle-and-solution-enthalpies-5.1-sq-medium-q2" class="nav-link" data-scroll-target="#example-5-lithium-fluoride-bornhaber-cycle-and-solution-enthalpies-5.1-sq-medium-q2">Example 5 · Lithium fluoride Born–Haber cycle and solution enthalpies · 5.1 SQ Medium Q2</a></li>
  <li><a href="#example-6-calcium-chloride-lattice-energy-and-calcium-malonate-5.1-sq-medium-q3" id="toc-example-6-calcium-chloride-lattice-energy-and-calcium-malonate-5.1-sq-medium-q3" class="nav-link" data-scroll-target="#example-6-calcium-chloride-lattice-energy-and-calcium-malonate-5.1-sq-medium-q3">Example 6 · Calcium chloride lattice energy and calcium malonate · 5.1 SQ Medium Q3</a></li>
  <li><a href="#example-7-hydration-enthalpy-and-the-experimental-determination-of-delta-h_mathrmsol-5.1-sq-medium-q4" id="toc-example-7-hydration-enthalpy-and-the-experimental-determination-of-delta-h_mathrmsol-5.1-sq-medium-q4" class="nav-link" data-scroll-target="#example-7-hydration-enthalpy-and-the-experimental-determination-of-delta-h_mathrmsol-5.1-sq-medium-q4">Example 7 · Hydration enthalpy and the experimental determination of <span class="math inline">\(\Delta H_{\mathrm{sol}}\)</span> · 5.1 SQ Medium Q4</a></li>
  <li><a href="#example-8-electron-affinity-and-the-electron-affinity-of-fluorine-5.1-sq-medium-q5" id="toc-example-8-electron-affinity-and-the-electron-affinity-of-fluorine-5.1-sq-medium-q5" class="nav-link" data-scroll-target="#example-8-electron-affinity-and-the-electron-affinity-of-fluorine-5.1-sq-medium-q5">Example 8 · Electron affinity and the electron affinity of fluorine · 5.1 SQ Medium Q5</a></li>
  <li><a href="#chemical-energetics---hard" id="toc-chemical-energetics---hard" class="nav-link" data-scroll-target="#chemical-energetics---hard">5.1 Chemical Energetics - Hard</a></li>
  <li><a href="#example-9-drawing-the-k₂s-bornhaber-cycle-and-calculating-lattice-enthalpy-5.1-sq-hard-q1" id="toc-example-9-drawing-the-k₂s-bornhaber-cycle-and-calculating-lattice-enthalpy-5.1-sq-hard-q1" class="nav-link" data-scroll-target="#example-9-drawing-the-k₂s-bornhaber-cycle-and-calculating-lattice-enthalpy-5.1-sq-hard-q1">Example 9 · Drawing the K₂S Born–Haber cycle and calculating lattice enthalpy · 5.1 SQ Hard Q1</a></li>
  <li><a href="#example-10-magnesium-oxide-and-the-second-ionisation-energy-of-magnesium-5.1-sq-hard-q2" id="toc-example-10-magnesium-oxide-and-the-second-ionisation-energy-of-magnesium-5.1-sq-hard-q2" class="nav-link" data-scroll-target="#example-10-magnesium-oxide-and-the-second-ionisation-energy-of-magnesium-5.1-sq-hard-q2">Example 10 · Magnesium oxide and the second ionisation energy of magnesium · 5.1 SQ Hard Q2</a></li>
  <li><a href="#example-11-sodium-selenide-cycle-and-the-lattice-energy-of-aluminium-oxide-5.1-sq-hard-q3" id="toc-example-11-sodium-selenide-cycle-and-the-lattice-energy-of-aluminium-oxide-5.1-sq-hard-q3" class="nav-link" data-scroll-target="#example-11-sodium-selenide-cycle-and-the-lattice-energy-of-aluminium-oxide-5.1-sq-hard-q3">Example 11 · Sodium selenide cycle and the lattice energy of aluminium oxide · 5.1 SQ Hard Q3</a></li>
  <li><a href="#example-12-identifying-a-group-1-ion-from-solution-data-5.1-sq-hard-q4" id="toc-example-12-identifying-a-group-1-ion-from-solution-data-5.1-sq-hard-q4" class="nav-link" data-scroll-target="#example-12-identifying-a-group-1-ion-from-solution-data-5.1-sq-hard-q4">Example 12 · Identifying a Group 1 ion from solution data · 5.1 SQ Hard Q4</a></li>
  <li><a href="#entropy---easy" id="toc-entropy---easy" class="nav-link" data-scroll-target="#entropy---easy">5.2 Entropy - Easy</a></li>
  <li><a href="#example-13-the-gibbs-equation-delta-s-and-minimum-temperature-5.2-sq-easy-q1" id="toc-example-13-the-gibbs-equation-delta-s-and-minimum-temperature-5.2-sq-easy-q1" class="nav-link" data-scroll-target="#example-13-the-gibbs-equation-delta-s-and-minimum-temperature-5.2-sq-easy-q1">Example 13 · The Gibbs equation, <span class="math inline">\(\Delta S\)</span> and minimum temperature · 5.2 SQ Easy Q1</a></li>
  <li><a href="#example-14-ammonium-chloride-dissociation-and-feasibility-5.2-sq-easy-q2" id="toc-example-14-ammonium-chloride-dissociation-and-feasibility-5.2-sq-easy-q2" class="nav-link" data-scroll-target="#example-14-ammonium-chloride-dissociation-and-feasibility-5.2-sq-easy-q2">Example 14 · Ammonium chloride dissociation and feasibility · 5.2 SQ Easy Q2</a></li>
  <li><a href="#example-15-melting-of-ice-5.2-sq-easy-q3" id="toc-example-15-melting-of-ice-5.2-sq-easy-q3" class="nav-link" data-scroll-target="#example-15-melting-of-ice-5.2-sq-easy-q3">Example 15 · Melting of ice · 5.2 SQ Easy Q3</a></li>
  <li><a href="#entropy---medium" id="toc-entropy---medium" class="nav-link" data-scroll-target="#entropy---medium">5.2 Entropy - Medium</a></li>
  <li><a href="#example-16-entropy-changes-and-the-decomposition-of-calcium-carbonate-5.2-sq-medium-q1" id="toc-example-16-entropy-changes-and-the-decomposition-of-calcium-carbonate-5.2-sq-medium-q1" class="nav-link" data-scroll-target="#example-16-entropy-changes-and-the-decomposition-of-calcium-carbonate-5.2-sq-medium-q1">Example 16 · Entropy changes and the decomposition of calcium carbonate · 5.2 SQ Medium Q1</a></li>
  <li><a href="#example-17-the-ostwald-process-5.2-sq-medium-q2" id="toc-example-17-the-ostwald-process-5.2-sq-medium-q2" class="nav-link" data-scroll-target="#example-17-the-ostwald-process-5.2-sq-medium-q2">Example 17 · The Ostwald process · 5.2 SQ Medium Q2</a></li>
  <li><a href="#example-18-potassium-nitrate-dissolving-5.2-sq-medium-q3" id="toc-example-18-potassium-nitrate-dissolving-5.2-sq-medium-q3" class="nav-link" data-scroll-target="#example-18-potassium-nitrate-dissolving-5.2-sq-medium-q3">Example 18 · Potassium nitrate dissolving · 5.2 SQ Medium Q3</a></li>
  <li><a href="#example-19-combustion-of-ethanol-5.2-sq-medium-q4" id="toc-example-19-combustion-of-ethanol-5.2-sq-medium-q4" class="nav-link" data-scroll-target="#example-19-combustion-of-ethanol-5.2-sq-medium-q4">Example 19 · Combustion of ethanol · 5.2 SQ Medium Q4</a></li>
  <li><a href="#entropy---hard" id="toc-entropy---hard" class="nav-link" data-scroll-target="#entropy---hard">5.2 Entropy - Hard</a></li>
  <li><a href="#example-20-methanol-synthesis-at-790-k-5.2-sq-hard-q1" id="toc-example-20-methanol-synthesis-at-790-k-5.2-sq-hard-q1" class="nav-link" data-scroll-target="#example-20-methanol-synthesis-at-790-k-5.2-sq-hard-q1">Example 20 · Methanol synthesis at 790 K · 5.2 SQ Hard Q1</a></li>
  <li><a href="#example-21-calcium-carbonate-stability-and-the-temperature-limits-of-feasibility-5.2-sq-hard-q2" id="toc-example-21-calcium-carbonate-stability-and-the-temperature-limits-of-feasibility-5.2-sq-hard-q2" class="nav-link" data-scroll-target="#example-21-calcium-carbonate-stability-and-the-temperature-limits-of-feasibility-5.2-sq-hard-q2">Example 21 · Calcium carbonate stability and the temperature limits of feasibility · 5.2 SQ Hard Q2</a></li>
  <li><a href="#example-22-predicting-signs-of-delta-s-and-the-temperature-for-so₂-oxidation-5.2-sq-hard-q3" id="toc-example-22-predicting-signs-of-delta-s-and-the-temperature-for-so₂-oxidation-5.2-sq-hard-q3" class="nav-link" data-scroll-target="#example-22-predicting-signs-of-delta-s-and-the-temperature-for-so₂-oxidation-5.2-sq-hard-q3">Example 22 · Predicting signs of <span class="math inline">\(\Delta S\)</span> and the temperature for SO₂ oxidation · 5.2 SQ Hard Q3</a></li>
  </ul></li>
  <li><a href="#chapter-checklist" id="toc-chapter-checklist" class="nav-link" data-scroll-target="#chapter-checklist">Chapter checklist</a>
  <ul class="collapse">
  <li><a href="#original-question-pdfs" id="toc-original-question-pdfs" class="nav-link" data-scroll-target="#original-question-pdfs">Original question PDFs</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../a-level/23-chemical-energetics.html">A Level</a></li><li class="breadcrumb-item"><a href="../a-level/23-chemical-energetics.html">23 Chemical energetics</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">23 Chemical energetics</h1>
<p class="subtitle lead">Lattice energy, Born–Haber cycles, solution and hydration enthalpies, entropy and Gibbs free energy</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>学完本章后，你应该能够：</p>
<ul>
<li>define and use enthalpy change of atomisation, lattice energy, electron affinity, enthalpy of solution and enthalpy of hydration;</li>
<li>construct and interpret Born–Haber cycles, and use them to calculate lattice energy;</li>
<li>explain the factors affecting lattice energy and enthalpy of hydration (ionic charge and ionic radius);</li>
<li>define entropy and predict whether entropy increases or decreases in a given process;</li>
<li>calculate standard entropy change <span class="math inline">\(\Delta S^\ominus\)</span> from standard entropy values;</li>
<li>use the Gibbs equation <span class="math inline">\(\Delta G^\ominus=\Delta H^\ominus-T\Delta S^\ominus\)</span> and judge reaction feasibility;</li>
<li>explain how temperature affects feasibility for different signs of <span class="math inline">\(\Delta H^\ominus\)</span> and <span class="math inline">\(\Delta S^\ominus\)</span>.</li>
</ul>
<hr>
</section>
<section id="lattice-energy-and-bornhaber-cycles" class="level2">
<h2 class="anchored" data-anchor-id="lattice-energy-and-bornhaber-cycles">23.1 Lattice energy and Born–Haber cycles</h2>
<section id="enthalpy-change-of-atomisation原子化焓变" class="level3 study-card">
<h3 class="anchored" data-anchor-id="enthalpy-change-of-atomisation原子化焓变">Enthalpy change of atomisation（原子化焓变）</h3>
<p><strong>The standard enthalpy change of atomisation, <span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}\)</span>, is the enthalpy change when 1 mole of gaseous atoms is formed from its element under standard conditions (298 K and 101 kPa).</strong></p>
<p>标准条件是本考纲统一使用的 298 K 温度与 101 kPa 压力。由于把元素拆成单个气态原子必然要破坏原子之间的键，<span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}\)</span> <strong>总是吸热（endothermic）、恒为正</strong>。</p>
<p>例如：</p>
<p><span class="math display">\[\mathrm{Na(s) \rightarrow Na(g)} \qquad \Delta H^\ominus_{\mathrm{at}}=+107\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p><span class="math display">\[\mathrm{Hg(l) \rightarrow Hg(g)} \qquad \Delta H^\ominus_{\mathrm{at}}=+61\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p>注意汞在标准状态下是液体，因此它的原子化焓是从液态变为气态。</p>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="写出原子化焓变的方程" class="level3">
<h3 class="anchored" data-anchor-id="写出原子化焓变的方程">写出原子化焓变的方程</h3>
<p>写出以下元素的 standard enthalpy change of atomisation 的方程：</p>
<ol type="1">
<li>Potassium（钾）</li>
<li>Mercury（汞）</li>
</ol>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<ol type="1">
<li><span class="math inline">\(\mathrm{K(s) \rightarrow K(g)}\)</span>：钾在标准状态下是固体；</li>
<li><span class="math inline">\(\mathrm{Hg(l) \rightarrow Hg(g)}\)</span>：汞在标准状态下是液体。</li>
</ol>
</div>
</section>
</div>
<section id="lattice-energy晶格能-晶格焓" class="level3 study-card">
<h3 class="anchored" data-anchor-id="lattice-energy晶格能-晶格焓">Lattice energy（晶格能 / 晶格焓）</h3>
<p><strong>The lattice energy, <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span>, is the enthalpy change when 1 mole of an ionic compound is formed from its gaseous ions, under standard conditions.</strong></p>
<p>晶格能描述的是「气态离子结合成 1 mol 离子晶体」这一过程。因为正负离子之间极强的静电吸引会释放大量能量，所以晶格能<strong>总是放热（exothermic）、恒为很大的负值</strong>。晶格能数值越负，说明晶格内离子键越强、晶体越稳定。</p>
<p>晶格能无法通过单一实验直接测定，需要用能量循环（energy cycle）间接计算。用方程式表示时，必须写对状态符号（state symbols）与离子电荷：</p>
<p><span class="math display">\[\mathrm{Mg^{2+}(g) + 2Cl^{-}(g) \rightarrow MgCl_2(s)} \qquad \Delta H^\ominus_{\mathrm{latt}} &lt; 0\]</span></p>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="写出晶格能的方程" class="level3">
<h3 class="anchored" data-anchor-id="写出晶格能的方程">写出晶格能的方程</h3>
<p>写出表示以下离子化合物 lattice energy 的方程：</p>
<ol type="1">
<li>Magnesium oxide（氧化镁）</li>
<li>Lithium chloride（氯化锂）</li>
</ol>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<ol type="1">
<li><span class="math inline">\(\mathrm{Mg^{2+}(g) + O^{2-}(g) \rightarrow MgO(s)}\)</span>；</li>
<li><span class="math inline">\(\mathrm{Li^{+}(g) + Cl^{-}(g) \rightarrow LiCl(s)}\)</span>。</li>
</ol>
</div>
</section>
</div>
<section id="electron-affinity电子亲和能" class="level3 formula-panel">
<h3 class="anchored" data-anchor-id="electron-affinity电子亲和能">Electron affinity（电子亲和能）</h3>
<p><strong>The first electron affinity, <span class="math inline">\(EA_1\)</span>, is the enthalpy change when 1 mole of electrons is added to 1 mole of gaseous atoms to form 1 mole of gaseous ions with a single negative charge, under standard conditions.</strong></p>
<p><span class="math display">\[X(g)+e^- \rightarrow X^-(g)\]</span></p>
<p>第一电子亲和能通常放热（exothermic、为负值），因为电子被原子核吸引会释放能量。</p>
<p><strong>The second electron affinity, <span class="math inline">\(EA_2\)</span>, is the enthalpy change when 1 mole of electrons is added to 1 mole of gaseous 1− ions to form 1 mole of gaseous 2− ions.</strong></p>
<p>第二、第三电子亲和能<strong>吸热（endothermic、为正值）</strong>，因为要把电子加到已经带负电的离子上，需要克服电子与负离子之间的斥力。</p>
</section>
<section id="影响电子亲和能的因素" class="level3 study-card">
<h3 class="anchored" data-anchor-id="影响电子亲和能的因素">影响电子亲和能的因素</h3>
<p>与电离能类似，电子亲和能的大小取决于原子核对外来电子的吸引强弱，受三个因素影响：</p>
<ul>
<li><strong>Nuclear charge（核电荷）</strong>：核电荷越大，吸引越强，<span class="math inline">\(EA_1\)</span> 越放热；</li>
<li><strong>Distance（距离）</strong>：外层电子离核越远，吸引越弱；</li>
<li><strong>Shielding（屏蔽效应）</strong>：电子层越多，屏蔽越强，吸引越弱。</li>
</ul>
<p><strong>Group 16 / 17 的纵向趋势</strong>：往下走 <span class="math inline">\(EA_1\)</span> 一般越来越不活泼（less exothermic），因为离子半径增大、屏蔽增强。例外是每族的第一个元素（氧、氟）：氟的原子半径很小、电子密度高，加入的电子与已有电子斥力大，所以 <span class="math inline">\(EA_1\)</span> 比氯更不活泼。</p>
</section>
<section id="bornhaber-cyclesbornhaber-循环" class="level3 study-card">
<h3 class="anchored" data-anchor-id="bornhaber-cyclesbornhaber-循环">Born–Haber cycles（Born–Haber 循环）</h3>
<p><strong>A Born–Haber cycle is a specific application of Hess’s Law to ionic compounds, used to calculate the lattice enthalpy which cannot be measured directly by experiment.</strong></p>
<p>循环的基本规则：</p>
<ul>
<li>图中能量向上增加（energy increases going up）；</li>
<li><strong>向上的箭头 = 吸热（endothermic），向下的箭头 = 放热（exothermic）</strong>；</li>
<li>起点通常画在约三分之一高度处，即元素在标准状态下的能量水平线；</li>
<li>循环通常包含：formation（生成）、atomisation（原子化）、ionisation（电离能）、electron affinity（电子亲和能）、lattice enthalpy（晶格焓）。</li>
</ul>
<p>下面是氯化钠的完整 Born–Haber 循环：</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-nacl-born-haber-cycle.webp" class="question-figure img-fluid figure-img" alt="Complete Born-Haber cycle for sodium chloride with labelled enthalpy changes"></p>
<figcaption>NaCl 的完整 Born–Haber 循环</figcaption>
</figure>
</div>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="构造-kcl-的-bornhaber-循环" class="level3">
<h3 class="anchored" data-anchor-id="构造-kcl-的-bornhaber-循环">构造 KCl 的 Born–Haber 循环</h3>
<p>构造一个可用于计算氯化钾晶格能的 Born–Haber 循环。每一步的焓变类型如下：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Enthalpy change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathrm{K(s) \rightarrow K(g)}\)</span></td>
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}(K)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{K(g) \rightarrow K^{+}(g) + e^-}\)</span></td>
<td>first ionisation energy</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{\tfrac{1}{2}Cl_2(g) \rightarrow Cl(g)}\)</span></td>
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}(Cl)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{Cl(g) + e^- \rightarrow Cl^{-}(g)}\)</span></td>
<td>first electron affinity</td>
</tr>
<tr class="odd">
<td>求和</td>
<td><span class="math inline">\(\Sigma\, \Delta H\)</span>（原子化 + 电离能 + 电子亲和能）</td>
</tr>
</tbody>
</table>
<p>再对晶格焓应用 Hess’s Law 即可求出 <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span>。</p>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-kcl-born-haber-cycle.webp" class="question-figure img-fluid figure-img" alt="Born-Haber cycle for potassium chloride"></p>
<figcaption>KCl 的 Born–Haber 循环（参考答案）</figcaption>
</figure>
</div>
<p>向上箭头代表吸热，向下箭头代表放热。直接路径（formation）与间接路径的焓变相等。</p>
</div>
</section>
</div>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="构造-mgo-的-bornhaber-循环" class="level3">
<h3 class="anchored" data-anchor-id="构造-mgo-的-bornhaber-循环">构造 MgO 的 Born–Haber 循环</h3>
<p>氧化镁涉及两个电离能和两个电子亲和能（氧的 <span class="math inline">\(EA_1\)</span> 与 <span class="math inline">\(EA_2\)</span>），循环比 KCl 多两步：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Enthalpy change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathrm{Mg(s) \rightarrow Mg(g)}\)</span></td>
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}(Mg)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{Mg(g) \rightarrow Mg^{+}(g) + e^-}\)</span></td>
<td><span class="math inline">\(IE_1\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{Mg^{+}(g) \rightarrow Mg^{2+}(g) + e^-}\)</span></td>
<td><span class="math inline">\(IE_2\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{\tfrac{1}{2}O_2(g) \rightarrow O(g)}\)</span></td>
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}(O)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{O(g) + e^- \rightarrow O^{-}(g)}\)</span></td>
<td><span class="math inline">\(EA_1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{O^{-}(g) + e^- \rightarrow O^{2-}(g)}\)</span></td>
<td><span class="math inline">\(EA_2\)</span></td>
</tr>
<tr class="odd">
<td>求和后再对晶格焓应用 Hess’s Law</td>
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span></td>
</tr>
</tbody>
</table>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-mgo-born-haber-cycle.webp" class="question-figure img-fluid figure-img" alt="Born-Haber cycle for magnesium oxide"></p>
<figcaption>MgO 的 Born–Haber 循环（参考答案）</figcaption>
</figure>
</div>
</div>
</section>
</div>
<section id="calculations-using-bornhaber-cyclesbornhaber-循环计算" class="level3 formula-panel">
<h3 class="anchored" data-anchor-id="calculations-using-bornhaber-cyclesbornhaber-循环计算">Calculations using Born–Haber cycles（Born–Haber 循环计算）</h3>
<p>根据 Hess’s Law，直接路径（formation）与间接路径（各分步焓变之和）相等：</p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{f}} = \Delta H^\ominus_{\mathrm{at}} + \sum IE + \sum EA + \Delta H^\ominus_{\mathrm{latt}}\]</span></p>
<p>整理得：</p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{latt}} = \Delta H^\ominus_{\mathrm{f}} - \Delta H^\ominus_{g \rightarrow \text{ions}}\]</span></p>
<p>其中 <span class="math inline">\(\Delta H^\ominus_{g \rightarrow \text{ions}}\)</span> 是所有把标准态元素变为气态离子的焓变之和（原子化 + 电离能 + 电子亲和能）。计算时<strong>务必按化学式的计量数乘以对应数值</strong>，例如 MgCl₂ 中有 2 mol 氯原子，氯的电子亲和能要乘 2。</p>
<p>以 KCl 为例：</p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{latt}}(KCl) = (-437) - [(+90) + (+122) + (+418) + (-349)] = -718\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p>括号能避免漏掉正负号，这是考试中最常见的失分点。</p>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="用数据计算-kcl-的晶格能" class="level3">
<h3 class="anchored" data-anchor-id="用数据计算-kcl-的晶格能">用数据计算 KCl 的晶格能</h3>
<p>用下面的数据计算氯化钾的晶格能 <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}(KCl)\)</span>：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(IE_1\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(EA_1\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\Delta H^\ominus_f\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>K</td>
<td style="text-align: right;">+90</td>
<td style="text-align: right;">+418</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Cl</td>
<td style="text-align: right;">+122</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−349</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>KCl</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−437</td>
</tr>
</tbody>
</table>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{latt}}(KCl) = \Delta H^\ominus_f - [\Delta H^\ominus_{at}(K) + \Delta H^\ominus_{at}(Cl) + IE_1(K) + EA_1(Cl)]\]</span></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{latt}}(KCl) = (-437) - [(+90) + (+122) + (+418) + (-349)] = -718\ \mathrm{kJ\,mol^{-1}}\]</span></p>
</div>
</section>
</div>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="用数据计算-mgo-的晶格能" class="level3">
<h3 class="anchored" data-anchor-id="用数据计算-mgo-的晶格能">用数据计算 MgO 的晶格能</h3>
<p>用下面的数据计算氧化镁的晶格能 <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}(MgO)\)</span>：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(IE_1\)</span> / <span class="math inline">\(IE_2\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(EA_1\)</span> / <span class="math inline">\(EA_2\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\Delta H^\ominus_f\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mg</td>
<td style="text-align: right;">+148</td>
<td style="text-align: right;">+736 / +1450</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>O</td>
<td style="text-align: right;">+248</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−142 / +770</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>MgO</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">−602</td>
</tr>
</tbody>
</table>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{latt}}(MgO) = \Delta H^\ominus_f - [\Delta H^\ominus_{at}(Mg) + \Delta H^\ominus_{at}(O) + IE_1(Mg) + IE_2(Mg) + EA_1(O) + EA_2(O)]\]</span></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{latt}}(MgO) = (-602) - [(+148) + (+248) + (+736) + (+1450) + (-142) + (+770)] = -3812\ \mathrm{kJ\,mol^{-1}}\]</span></p>
</div>
</section>
</div>
<section id="影响晶格能的因素离子电荷与离子半径" class="level3 study-card">
<h3 class="anchored" data-anchor-id="影响晶格能的因素离子电荷与离子半径">影响晶格能的因素：离子电荷与离子半径</h3>
<ul>
<li><strong>Ionic radius（离子半径）</strong>：离子半径越大，晶格能越不活泼（less exothermic）。大离子电荷分布更分散，且离子中心间距更大，正负离子间静电吸引更弱；</li>
<li><strong>Ionic charge（离子电荷）</strong>：离子电荷越高，charge density 越大，静电吸引越强，晶格能越活泼（more exothermic）。</li>
</ul>
<p>例如 CsF 的晶格能（−730 kJ mol⁻¹）比 KF（−830 kJ mol⁻¹）不活泼，因为 Cs⁺ 比 K⁺ 大、与 F⁻ 的距离更远；而 CaO（2+ / 2− 离子）比 KCl（1+ / 1−）活泼得多。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-lattice-energy-vs-radius.webp" class="question-figure img-fluid figure-img" alt="Lattice energy becomes less exothermic as ionic radius increases"></p>
<figcaption>晶格能与离子半径的关系</figcaption>
</figure>
</div>
</section>
<hr>
</section>
<section id="enthalpies-of-solution-and-hydration" class="level2">
<h2 class="anchored" data-anchor-id="enthalpies-of-solution-and-hydration">23.2 Enthalpies of solution and hydration</h2>
<section id="enthalpy-change-of-solution溶解焓变" class="level3 study-card">
<h3 class="anchored" data-anchor-id="enthalpy-change-of-solution溶解焓变">Enthalpy change of solution（溶解焓变）</h3>
<p><strong>The standard enthalpy change of solution, <span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}}\)</span>, is the enthalpy change when 1 mole of an ionic substance dissolves in sufficient water to form a very dilute solution.</strong></p>
<p><span class="math display">\[\mathrm{KCl(s) + aq \rightarrow K^+(aq) + Cl^-(aq)}\]</span></p>
<p><span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}}\)</span> 可正可负（放热或吸热溶解）。</p>
</section>
<section id="enthalpy-change-of-hydration水合焓变" class="level3 study-card">
<h3 class="anchored" data-anchor-id="enthalpy-change-of-hydration水合焓变">Enthalpy change of hydration（水合焓变）</h3>
<p><strong>The standard enthalpy change of hydration, <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span>, is the enthalpy change when 1 mole of a specified gaseous ion dissolves in sufficient water to form a very dilute solution.</strong></p>
<p><span class="math display">\[\mathrm{Mg^{2+}(g) + aq \rightarrow Mg^{2+}(aq)}\]</span></p>
<p>水是极性分子，氧端带 <span class="math inline">\(\delta^-\)</span>、氢端带 <span class="math inline">\(\delta^+\)</span>。正离子吸引水中带 <span class="math inline">\(\delta^-\)</span> 的氧，负离子吸引带 <span class="math inline">\(\delta^+\)</span> 的氢，形成 ion–dipole attractions。<strong>水合焓总是放热（exothermic、为负值）</strong>。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-hydration-water-ions.webp" class="question-figure img-fluid figure-img" alt="Polar water molecules form ion-dipole bonds with K+ and Cl- ions"></p>
<figcaption>极性水分子与离子的相互作用（离子水合）</figcaption>
</figure>
</div>
</section>
<section id="溶解焓与水合焓的能量循环" class="level3 formula-panel">
<h3 class="anchored" data-anchor-id="溶解焓与水合焓的能量循环">溶解焓与水合焓的能量循环</h3>
<p>离子晶体溶于水可以走两条路径：</p>
<ul>
<li>直接路径：<span class="math inline">\(\mathrm{ionic\ lattice \rightarrow hydrated\ ions}\)</span>，即 <span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}}\)</span>；</li>
<li>间接路径：先破坏晶格（lattice dissociation，<span class="math inline">\(-\Delta H^\ominus_{\mathrm{latt}}\)</span>，吸热），再让气态离子水合（hydration，<span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span>，放热）。</li>
</ul>
<p>由 Hess’s Law：</p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{sol}} = -\Delta H^\ominus_{\mathrm{latt}} + \Sigma\, \Delta H^\ominus_{\mathrm{hyd}}\]</span></p>
<p>注意：总水合焓要<strong>把每种离子的水合焓加起来</strong>，并乘以化学式中的离子个数。例如 MgCl₂ 中有 2 mol Cl⁻，氯离子水合焓要乘 2。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-solution-energy-cycle.webp" class="question-figure img-fluid figure-img" alt="Energy cycle linking lattice energy, hydration enthalpies and enthalpy of solution"></p>
<figcaption>溶解焓–晶格能–水合焓的能量循环</figcaption>
</figure>
</div>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="用能量循环求-kcl-中氯离子的水合焓" class="level3">
<h3 class="anchored" data-anchor-id="用能量循环求-kcl-中氯离子的水合焓">用能量循环求 KCl 中氯离子的水合焓</h3>
<p>构造能量循环与能量水平图，计算氯化钾中 <span class="math inline">\(\mathrm{Cl^-}\)</span> 离子的 <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span>。</p>
<p>已知：<span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}(KCl) = -711\ \mathrm{kJ\,mol^{-1}}\)</span>，<span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}}(KCl) = +26\ \mathrm{kJ\,mol^{-1}}\)</span>，<span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}(K^+) = -322\ \mathrm{kJ\,mol^{-1}}\)</span>。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/kcl-energy-cycle.webp" class="question-figure img-fluid figure-img" alt="Energy cycle for the hydration of potassium chloride"></p>
<figcaption>KCl 的能量循环</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/kcl-energy-level.webp" class="question-figure img-fluid figure-img" alt="Energy level diagram for the hydration of potassium chloride"></p>
<figcaption>KCl 的能量水平图</figcaption>
</figure>
</div>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{hyd}}(Cl^-) = \Delta H^\ominus_{\mathrm{sol}} + \Delta H^\ominus_{\mathrm{latt}} - \Delta H^\ominus_{\mathrm{hyd}}(K^+)\]</span></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{hyd}}(Cl^-) = (+26) + (-711) - (-322) = -363\ \mathrm{kJ\,mol^{-1}}\]</span></p>
</div>
</section>
</div>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="用能量循环求-mgcl₂-中镁离子的水合焓" class="level3">
<h3 class="anchored" data-anchor-id="用能量循环求-mgcl₂-中镁离子的水合焓">用能量循环求 MgCl₂ 中镁离子的水合焓</h3>
<p>构造能量循环与能量水平图，计算 <span class="math inline">\(\mathrm{MgCl_2}\)</span> 中 <span class="math inline">\(\mathrm{Mg^{2+}}\)</span> 离子的 <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span>。</p>
<p>已知：<span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}(MgCl_2) = -2592\ \mathrm{kJ\,mol^{-1}}\)</span>，<span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}}(MgCl_2) = -55\ \mathrm{kJ\,mol^{-1}}\)</span>，<span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}(Cl^-) = -363\ \mathrm{kJ\,mol^{-1}}\)</span>。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/mgcl2-energy-cycle.webp" class="question-figure img-fluid figure-img" alt="Energy cycle for the hydration of magnesium chloride"></p>
<figcaption>MgCl₂ 的能量循环（注意 Cl⁻ 要乘 2）</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-mgcl2-energy-level.webp" class="question-figure img-fluid figure-img" alt="Energy level diagram for the hydration of magnesium chloride"></p>
<figcaption>MgCl₂ 的能量水平图</figcaption>
</figure>
</div>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{hyd}}(Mg^{2+}) = \Delta H^\ominus_{\mathrm{sol}} + \Delta H^\ominus_{\mathrm{latt}} - 2 \times \Delta H^\ominus_{\mathrm{hyd}}(Cl^-)\]</span></p>
<p><span class="math display">\[\Delta H^\ominus_{\mathrm{hyd}}(Mg^{2+}) = (-55) + (-2592) - 2 \times (-363) = -1921\ \mathrm{kJ\,mol^{-1}}\]</span></p>
</div>
</section>
</div>
<section id="影响水合焓的因素" class="level3 study-card">
<h3 class="anchored" data-anchor-id="影响水合焓的因素">影响水合焓的因素</h3>
<ul>
<li><strong>Ionic radius</strong>：离子越小，charge density 越大，与水分子之间的 ion–dipole 吸引越强，水合焓越活泼（more exothermic）；</li>
<li><strong>Ionic charge</strong>：离子电荷越高，水合焓越活泼。</li>
</ul>
<p>例如 Mg²⁺ 比 Ca²⁺ 小，Mg²⁺ 的水合焓更活泼；MgSO₄ 比 BaSO₄ 的水合焓更活泼（SO₄²⁻ 相同，Mg²⁺ 更小）。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-hydration-compare.webp" class="question-figure img-fluid figure-img" alt="Hydration enthalpy is more exothermic for smaller ions and ions with larger charge"></p>
<figcaption>比较不同离子的水合焓</figcaption>
</figure>
</div>
</section>
<hr>
</section>
<section id="entropy-change" class="level2">
<h2 class="anchored" data-anchor-id="entropy-change">23.3 Entropy change</h2>
<section id="entropy熵" class="level3 study-card">
<h3 class="anchored" data-anchor-id="entropy熵">Entropy（熵）</h3>
<p><strong>Entropy, <span class="math inline">\(S\)</span>, is the number of possible arrangements of the particles and their energy in a given system — in other words, a measure of how disordered a system is.</strong></p>
<p>系统越无序，熵越大；系统越无序，能量上越稳定。不同状态的熵大小顺序为：</p>
<p><span class="math display">\[\mathrm{gas &gt; liquid &gt; solid}\]</span></p>
<p>典型规律：</p>
<ul>
<li>熔化（solid → liquid）与沸腾（liquid → gas）：熵增加；</li>
<li>凝固与冷凝：熵减少；</li>
<li>固体溶解成稀溶液：熵增加（粒子更分散、排列能量方式更多）；</li>
<li>从溶液中结晶析出：熵减少；</li>
<li>反应中气体分子数增加：熵增加；气体分子数减少：熵减少。例如 <span class="math inline">\(\mathrm{N_2(g)+3H_2(g)\rightleftharpoons 2NH_3(g)}\)</span>，4 mol 气体变成 2 mol 气体，熵减少。</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-entropy-vs-temperature.webp" class="question-figure img-fluid figure-img" alt="Graph of entropy against temperature showing melting and boiling points"></p>
<figcaption>熵随温度的变化（熔化与沸腾）</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-entropy-dissolving.webp" class="question-figure img-fluid figure-img" alt="Dissolving a solid in a solvent increases entropy"></p>
<figcaption>固体溶解过程的熵变</figcaption>
</figure>
</div>
</section>
<section id="标准熵变计算" class="level3 formula-panel">
<h3 class="anchored" data-anchor-id="标准熵变计算">标准熵变计算</h3>
<p><span class="math display">\[\Delta S^\ominus_{\mathrm{system}} = \Sigma\, S^\ominus_{\mathrm{products}} - \Sigma\, S^\ominus_{\mathrm{reactants}}\]</span></p>
<p>计算时按方程式计量数乘以对应物质的 <span class="math inline">\(S^\ominus\)</span>，并注意物质的状态。</p>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="计算反应的熵变" class="level3">
<h3 class="anchored" data-anchor-id="计算反应的熵变">计算反应的熵变</h3>
<p>计算 <span class="math inline">\(\mathrm{2Mg(s) + O_2(g) \rightarrow 2MgO(s)}\)</span> 的熵变：</p>
<p><span class="math inline">\(S^\ominus[\mathrm{Mg(s)}] = 32.60\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(S^\ominus[\mathrm{O_2(g)}] = 205.0\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(S^\ominus[\mathrm{MgO(s)}] = 38.20\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>。</p>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p><span class="math display">\[\Delta S^\ominus_{\mathrm{system}} = \Sigma\, S^\ominus_{products} - \Sigma\, S^\ominus_{reactants}\]</span></p>
<p><span class="math display">\[\Delta S^\ominus_{\mathrm{system}} = (2 \times 38.20) - (2 \times 32.60 + 205.0) = -193.8\ \mathrm{J\,K^{-1}\,mol^{-1}}\]</span></p>
<p>反应中 3 mol 气体变成 2 mol 固体，气体分子数减少，所以熵变是负的。</p>
</div>
</section>
</div>
<hr>
</section>
<section id="gibbs-free-energy-change" class="level2">
<h2 class="anchored" data-anchor-id="gibbs-free-energy-change">23.4 Gibbs free energy change</h2>
<section id="the-gibbs-equationgibbs-方程" class="level3 formula-panel">
<h3 class="anchored" data-anchor-id="the-gibbs-equationgibbs-方程">The Gibbs equation（Gibbs 方程）</h3>
<p><span class="math display">\[\Delta G^\ominus = \Delta H^\ominus_{\mathrm{reaction}} - T\Delta S^\ominus_{\mathrm{system}}\]</span></p>
<p>单位：<span class="math inline">\(\Delta G^\ominus\)</span> 与 <span class="math inline">\(\Delta H^\ominus\)</span> 用 <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span>，<span class="math inline">\(T\)</span> 用 K，<span class="math inline">\(\Delta S^\ominus\)</span> 用 <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span>。<strong>代入前必须把 <span class="math inline">\(\Delta S^\ominus\)</span> 除以 1000 换成 <span class="math inline">\(\mathrm{kJ\,K^{-1}\,mol^{-1}}\)</span></strong>，这是最常见的失分点。</p>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="计算碳酸氢钠分解的-delta-gominus" class="level3">
<h3 class="anchored" data-anchor-id="计算碳酸氢钠分解的-delta-gominus">计算碳酸氢钠分解的 <span class="math inline">\(\Delta G^\ominus\)</span></h3>
<p><span class="math display">\[\mathrm{2NaHCO_3(s) \rightarrow Na_2CO_3(s) + H_2O(l) + CO_2(g)}\]</span></p>
<p>已知 <span class="math inline">\(\Delta H^\ominus = +135\ \mathrm{kJ\,mol^{-1}}\)</span>，<span class="math inline">\(\Delta S^\ominus = +344\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，计算 298 K 下的 <span class="math inline">\(\Delta G^\ominus\)</span>。</p>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p>先把熵变换成 <span class="math inline">\(\mathrm{kJ}\)</span>：<span class="math inline">\(\Delta S^\ominus = 344/1000 = +0.344\ \mathrm{kJ\,K^{-1}\,mol^{-1}}\)</span>；</p>
<p><span class="math display">\[\Delta G^\ominus = \Delta H^\ominus - T\Delta S^\ominus = +135 - (298 \times 0.344) = +32.49\ \mathrm{kJ\,mol^{-1}}\]</span></p>
</div>
</section>
</div>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="计算甲醇与-hbr-反应的-delta-gominus" class="level3">
<h3 class="anchored" data-anchor-id="计算甲醇与-hbr-反应的-delta-gominus">计算甲醇与 HBr 反应的 <span class="math inline">\(\Delta G^\ominus\)</span></h3>
<p><span class="math display">\[\mathrm{CH_3OH(l) + HBr(g) \rightarrow CH_3Br(g) + H_2O(l)}\]</span></p>
<p><span class="math inline">\(S^\ominus[\mathrm{CH_3OH(l)}] = +240\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(S^\ominus[\mathrm{HBr(g)}] = +99.0\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(S^\ominus[\mathrm{H_2O(l)}] = +70.0\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(S^\ominus[\mathrm{CH_3Br(g)}] = +246\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(\Delta H^\ominus = -47\ \mathrm{kJ\,mol^{-1}}\)</span>。</p>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p><span class="math display">\[\Delta S^\ominus_{\mathrm{system}} = (246 + 70.0) - (240 + 99.0) = -23.0\ \mathrm{J\,K^{-1}\,mol^{-1}}\]</span></p>
<p><span class="math display">\[\Delta G^\ominus = (-47) - 298 \times (-0.023) = -40.1\ \mathrm{kJ\,mol^{-1}}\]</span></p>
</div>
</section>
</div>
<section id="reaction-feasibility反应可行性" class="level3 study-card">
<h3 class="anchored" data-anchor-id="reaction-feasibility反应可行性">Reaction feasibility（反应可行性）</h3>
<p><strong>When <span class="math inline">\(\Delta G^\ominus\)</span> is negative, the reaction is feasible and likely to occur; when <span class="math inline">\(\Delta G^\ominus\)</span> is positive, the reaction is not feasible and unlikely to occur.</strong></p>
<p>仅看熵变不足以判断可行性，必须同时考虑焓变，Gibbs 方程把两者合在一起。</p>
<p>温度对可行性的影响由 <span class="math inline">\(\Delta H^\ominus\)</span> 与 <span class="math inline">\(\Delta S^\ominus\)</span> 的符号决定，共四种情况：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\Delta H^\ominus\)</span></th>
<th><span class="math inline">\(\Delta S^\ominus\)</span></th>
<th><span class="math inline">\(\Delta G^\ominus\)</span></th>
<th>可行性</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>negative（放热）</td>
<td>positive（更无序）</td>
<td>任何温度都为负</td>
<td><strong>任何温度都可行</strong></td>
</tr>
<tr class="even">
<td>negative（放热）</td>
<td>negative（更有序）</td>
<td>低温为负、高温为正</td>
<td>只在低温可行</td>
</tr>
<tr class="odd">
<td>positive（吸热）</td>
<td>negative（更有序）</td>
<td>任何温度都为正</td>
<td><strong>任何温度都不可行</strong></td>
</tr>
<tr class="even">
<td>positive（吸热）</td>
<td>positive（更无序）</td>
<td>高温为负、低温为正</td>
<td>只在高温可行</td>
</tr>
</tbody>
</table>
<p>例如碳酸钙热分解 <span class="math inline">\(\mathrm{CaCO_3(s)\rightarrow CaO(s)+CO_2(g)}\)</span>，<span class="math inline">\(\Delta H^\ominus=+178\ \mathrm{kJ\,mol^{-1}}\)</span>、<span class="math inline">\(\Delta S^\ominus=+160.9\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，两者都为正，所以只有高温才可行——升高温度后 <span class="math inline">\(T\Delta S\)</span> 超过 <span class="math inline">\(\Delta H\)</span>，<span class="math inline">\(\Delta G\)</span> 变为负。</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../assets/notes/chemical-energetics/note-gibbs-exothermic-summary.webp" class="question-figure img-fluid figure-img" alt="Summary of factors affecting Gibbs free energy for exothermic reactions"></p>
<figcaption>放热反应的可行性总结表（来自笔记）</figcaption>
</figure>
</div>
</section>
<div class="worked-example">
<p><span class="we-tag">Worked example · 笔记例题</span></p>
<section id="判断-2ca-o₂-反应的可行性" class="level3">
<h3 class="anchored" data-anchor-id="判断-2ca-o₂-反应的可行性">判断 2Ca + O₂ 反应的可行性</h3>
<p><span class="math display">\[\mathrm{2Ca(s) + O_2(g) \rightarrow 2CaO(s)} \qquad \Delta H^\ominus = -635.5\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p><span class="math inline">\(S^\ominus[\mathrm{Ca(s)}] = 41.00\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(S^\ominus[\mathrm{O_2(g)}] = 205.0\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>，<span class="math inline">\(S^\ominus[\mathrm{CaO(s)}] = 40.00\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>。</p>
<div class="we-answer">
<p><strong>Answer:</strong></p>
<p><span class="math display">\[\Delta S^\ominus_{\mathrm{system}} = (2 \times 40.00) - (2 \times 41.00 + 205.0) = -207.0\ \mathrm{J\,K^{-1}\,mol^{-1}}\]</span></p>
<p><span class="math display">\[\Delta G^\ominus = (-635.5) - 298 \times (-0.207) = -573.8\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p><span class="math inline">\(\Delta G^\ominus\)</span> 为负，所以该反应可行（feasible），且任何温度下都可行。</p>
</div>
</section>
</div>
<hr>
</section>
<section id="structured-questions" class="level2">
<h2 class="anchored" data-anchor-id="structured-questions">Structured Questions</h2>
<section id="chemical-energetics---easy" class="level3">
<h3 class="anchored" data-anchor-id="chemical-energetics---easy">5.1 Chemical Energetics - Easy</h3>
</section>
<section id="example-1-lattice-energy-and-the-cao-bornhaber-cycle-5.1-sq-easy-q1" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-1-lattice-energy-and-the-cao-bornhaber-cycle-5.1-sq-easy-q1">Example 1 · Lattice energy and the CaO Born–Haber cycle · 5.1 SQ Easy Q1</h3>
<p>This question is about the formation of calcium oxide.</p>
<p><strong>(a)</strong> Explain the meaning of the term <strong>lattice energy</strong>. <code>[3 marks]</code></p>
<p><strong>(b)</strong> The Born–Haber cycle in Fig. 1.1 can be used to determine the lattice enthalpy of calcium oxide. Steps A–G include the values for enthalpy changes.</p>
<p>Complete the Born–Haber cycle by adding the species present on the two dotted lines. Include state symbols.</p>
<p><img src="../assets/questions/chemical-energetics/cao-born-haber-cycle.webp" class="question-figure img-fluid" alt="Born-Haber cycle for calcium oxide with dotted lines at steps E and G"></p>
<p><code>[2 marks]</code></p>
<p><strong>(c)</strong> Name the enthalpy changes for the following steps in the Born–Haber cycle.</p>
<ul>
<li>Step B</li>
<li>Step D</li>
<li>Step F</li>
</ul>
<p><code>[3 marks]</code></p>
<p><strong>(d)</strong> Step C represents the enthalpy change of atomisation of oxygen. Why is the enthalpy change of atomisation always a positive value? <code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> The formation of 1 mole of an ionic lattice <code>[1]</code> from gaseous ions <code>[1]</code> under standard conditions. <code>[1]</code></li>
<li><strong>(b)</strong> Step E: <span class="math inline">\(\mathrm{Ca^{2+}(g) + O(g) + 2e^-}\)</span> <code>[1]</code>; Step G: <span class="math inline">\(\mathrm{Ca^{2+}(g) + O^{2-}(g)}\)</span>. <code>[1]</code></li>
<li><strong>(c)</strong> Step B: enthalpy of atomisation (of calcium) <code>[1]</code>; Step D: first ionisation energy of calcium <code>[1]</code>; Step F: first electron affinity of oxygen. <code>[1]</code></li>
<li><strong>(d)</strong> Energy is taken in to break the bonds <code>[1]</code>; (so) the process is endothermic. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-2-potassium-fluoride-cycle-and-enthalpy-of-solution-5.1-sq-easy-q2" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-2-potassium-fluoride-cycle-and-enthalpy-of-solution-5.1-sq-easy-q2">Example 2 · Potassium fluoride cycle and enthalpy of solution · 5.1 SQ Easy Q2</h3>
<p>This question is about lattice enthalpy.</p>
<p><strong>(a)</strong> Write one equation to represent the following changes:</p>
<ul>
<li>atomisation of sodium;</li>
<li>second ionisation energy of magnesium;</li>
<li>first electron affinity of chlorine.</li>
</ul>
<p><code>[3 marks]</code></p>
<p><strong>(b)</strong> The Born–Haber cycle for the formation of potassium fluoride is shown in Fig. 2.1.</p>
<p><img src="../assets/questions/chemical-energetics/kf-born-haber-cycle.webp" class="question-figure img-fluid" alt="Born-Haber cycle for potassium fluoride with steps 1 to 6 labelled"></p>
<p>Complete Table 2.1 by naming the enthalpy changes associated with the identified steps.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Name of the enthalpy change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>Atomisation of potassium</td>
</tr>
<tr class="odd">
<td>3</td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td>First ionisation energy of potassium</td>
</tr>
<tr class="odd">
<td>5</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td>Lattice enthalpy of formation</td>
</tr>
</tbody>
</table>
<p><code>[3 marks]</code></p>
<p><strong>(c)</strong> The enthalpies of lattice formation for potassium fluoride and caesium fluoride are <span class="math inline">\(-830\ \mathrm{kJ\,mol^{-1}}\)</span> and <span class="math inline">\(-730\ \mathrm{kJ\,mol^{-1}}\)</span> respectively.</p>
<p>Explain why the enthalpy of lattice formation is more exothermic for potassium fluoride. <code>[3 marks]</code></p>
<p><strong>(d)</strong> Use the data in Table 2.2 to calculate the enthalpy of solution of potassium fluoride.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Enthalpy change</th>
<th>Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> KF</td>
<td>−830</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span> K⁺</td>
<td>−351</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span> F⁻</td>
<td>−504</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}}\)</span> KF</td>
<td><span class="math inline">\(x\)</span></td>
</tr>
</tbody>
</table>
<p><code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\mathrm{Na(s) \rightarrow Na(g)}\)</span> <code>[1]</code>; <span class="math inline">\(\mathrm{Mg^{+}(g) \rightarrow Mg^{2+}(g) + e^-}\)</span> <code>[1]</code>; <span class="math inline">\(\mathrm{Cl(g) + e^- \rightarrow Cl^{-}(g)}\)</span>. <code>[1]</code></li>
<li><strong>(b)</strong> Step 1: enthalpy change of formation <code>[1]</code>; Step 3: atomisation of fluorine <code>[1]</code>; Step 5: first electron affinity of fluorine. <code>[1]</code></li>
<li><strong>(c)</strong> The potassium ion is smaller than the caesium ion / K⁺ has fewer electron shells <code>[1]</code>; the distance between the potassium ion and fluoride ion is shorter <code>[1]</code>; so the K–F bonding is stronger. <code>[1]</code></li>
<li><strong>(d)</strong> <span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}} = \Delta H^\ominus_{\mathrm{hyd}}(K^+) + \Delta H^\ominus_{\mathrm{hyd}}(F^-) - \Delta H^\ominus_{\mathrm{latt}}\)</span> <code>[1]</code> <span class="math inline">\(= (-351) + (-504) - (-830)\)</span> <code>[1]</code> <span class="math inline">\(= -25\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-3-nacl-lattice-enthalpy-electron-affinity-and-the-arrows-for-oxygen-5.1-sq-easy-q3" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-3-nacl-lattice-enthalpy-electron-affinity-and-the-arrows-for-oxygen-5.1-sq-easy-q3">Example 3 · NaCl lattice enthalpy, electron affinity and the arrows for oxygen · 5.1 SQ Easy Q3</h3>
<p>This question is about enthalpy changes and calculations.</p>
<p><strong>(a)</strong> Table 3.1 shows the enthalpy data for the formation of sodium chloride.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Enthalpy change</th>
<th>Equation</th>
<th style="text-align: right;">Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{f}}\)</span> NaCl</td>
<td><span class="math inline">\(\mathrm{Na(s) + \tfrac{1}{2}Cl_2(g) \rightarrow NaCl(s)}\)</span></td>
<td style="text-align: right;">−411</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}\)</span> Cl</td>
<td><span class="math inline">\(\mathrm{\tfrac{1}{2}Cl_2(g) \rightarrow Cl(g)}\)</span></td>
<td style="text-align: right;">+121</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{at}}\)</span> Na</td>
<td><span class="math inline">\(\mathrm{Na(s) \rightarrow Na(g)}\)</span></td>
<td style="text-align: right;">+108</td>
</tr>
<tr class="even">
<td><span class="math inline">\(E_{ea}\)</span> Cl</td>
<td><span class="math inline">\(\mathrm{Cl(g) \rightarrow Cl^{-}(g)}\)</span></td>
<td style="text-align: right;">−349</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_{ie}\)</span> Na</td>
<td><span class="math inline">\(\mathrm{Na(g) \rightarrow Na^{+}(g)}\)</span></td>
<td style="text-align: right;">+496</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> NaCl</td>
<td><span class="math inline">\(\mathrm{Na^{+}(g) + Cl^{-}(g) \rightarrow NaCl(s)}\)</span></td>
<td style="text-align: right;">to be calculated</td>
</tr>
</tbody>
</table>
<p>Calculate the enthalpy of lattice formation of sodium chloride. <code>[3 marks]</code></p>
<p><strong>(b)</strong> State the definition of electron affinity. <code>[3 marks]</code></p>
<p><strong>(c)</strong> A section of the Born–Haber cycle for the formation of magnesium oxide is shown in Fig. 3.1.</p>
<p><img src="../assets/questions/chemical-energetics/mgo-ea-arrows.webp" class="question-figure img-fluid" alt="Section of the Born-Haber cycle for magnesium oxide showing first and second electron affinity arrows for oxygen"></p>
<p>The first electron affinity of oxygen has a negative value so the arrow points downwards. The second electron affinity of oxygen has a positive value so the arrow points upwards.</p>
<p>Explain why the arrows point in different directions. <code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}(NaCl) = \Delta H^\ominus_{\mathrm{f}} - [\Delta H^\ominus_{\mathrm{at}}(Na) + \Delta H^\ominus_{\mathrm{at}}(Cl) + \Delta H^\ominus_{ie}(Na) + E_{ea}(Cl)]\)</span> <code>[1]</code> <span class="math inline">\(= -411 - (108 + 121 + 496 - 349)\)</span> <code>[1]</code> <span class="math inline">\(= -787\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(b)</strong> The electron affinity of an element is the energy change when 1 mole of electrons is gained <code>[1]</code> by 1 mole of gaseous atoms to form 1 mole of gaseous 1− ions <code>[1]</code> under standard conditions. <code>[1]</code></li>
<li><strong>(c)</strong> The first electron affinity of oxygen is exothermic <code>[1]</code>; the second electron affinity of oxygen is endothermic <code>[1]</code>; because the repulsion between the incoming electron and the negative ion must be overcome. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="chemical-energetics---medium" class="level3">
<h3 class="anchored" data-anchor-id="chemical-energetics---medium">5.1 Chemical Energetics - Medium</h3>
</section>
<section id="example-4-lattice-energy-of-potassium-oxide-5.1-sq-medium-q1" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-4-lattice-energy-of-potassium-oxide-5.1-sq-medium-q1">Example 4 · Lattice energy of potassium oxide · 5.1 SQ Medium Q1</h3>
<p>Lattice energies are always negative showing that they represent exothermic changes.</p>
<p><strong>(a)</strong></p>
<p><strong>(i)</strong> Explain what is meant by lattice energy. <code>[2]</code></p>
<p><strong>(ii)</strong> Explain why lattice energy is an exothermic process. <code>[1]</code></p>
<p><code>[3 marks]</code></p>
<p><strong>(b)</strong></p>
<p><strong>(i)</strong> Use relevant data from Table 5.1 to calculate the lattice energy, <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span>, of potassium oxide, <span class="math inline">\(\mathrm{K_2O(s)}\)</span>. Show your working.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Energy change</th>
<th style="text-align: right;">Value / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard enthalpy change of atomisation of potassium</td>
<td style="text-align: right;">+89</td>
</tr>
<tr class="even">
<td>Electron affinity of <span class="math inline">\(\mathrm{O(g)}\)</span></td>
<td style="text-align: right;">−141</td>
</tr>
<tr class="odd">
<td>Electron affinity of <span class="math inline">\(\mathrm{O^-(g)}\)</span></td>
<td style="text-align: right;">+798</td>
</tr>
<tr class="even">
<td>Standard enthalpy change of formation of potassium oxide</td>
<td style="text-align: right;">−361</td>
</tr>
<tr class="odd">
<td>First ionisation energy of potassium</td>
<td style="text-align: right;">+418</td>
</tr>
<tr class="even">
<td>Second ionisation energy of potassium</td>
<td style="text-align: right;">+3070</td>
</tr>
<tr class="odd">
<td>First ionisation energy of oxygen</td>
<td style="text-align: right;">+1310</td>
</tr>
<tr class="even">
<td>Second ionisation energy of oxygen</td>
<td style="text-align: right;">+3390</td>
</tr>
<tr class="odd">
<td>O=O bond energy (diatomic molecule)</td>
<td style="text-align: right;">+496</td>
</tr>
<tr class="even">
<td>O–O bond energy (polyatomic molecule)</td>
<td style="text-align: right;">+150</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> of <span class="math inline">\(\mathrm{K_2O(s)} = \underline{\hspace{6em}}\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[3]</code></p>
<p><strong>(ii)</strong> State how <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{Na_2O(s)}\)</span> differs from <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{K_2O(s)}\)</span>. Indicate this by placing one tick (✓) in the appropriate box in Table 5.2. Explain your answer.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{Na_2O(s)}\)</span> is less negative than <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{K_2O(s)}\)</span></th>
<th><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{Na_2O(s)}\)</span> is the same as <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{K_2O(s)}\)</span></th>
<th><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{Na_2O(s)}\)</span> is more negative than <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{K_2O(s)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><code>[4 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)(i)</strong> (The energy change) when 1 mole of an ionic compound is formed <code>[1]</code> from gaseous ions (under standard conditions). <code>[1]</code></li>
<li><strong>(a)(ii)</strong> Forming an ionic bond <code>[1]</code> releases a large amount of energy.</li>
<li><strong>(b)(i)</strong> <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}} = -361 - [2(+89) + \tfrac{1}{2}(+496) + 2(+418) + (-141) + (+798)]\)</span> — correct data extraction and multipliers <code>[1]</code> <span class="math inline">\(= -361 - 1919\)</span> <code>[1]</code> <span class="math inline">\(= -2280\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(b)(ii)</strong> Tick the third box: <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{Na_2O(s)}\)</span> is more negative <code>[1]</code> because sodium has a smaller ionic radius <code>[1]</code>, so there is greater attraction between the ions. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-5-lithium-fluoride-bornhaber-cycle-and-solution-enthalpies-5.1-sq-medium-q2" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-5-lithium-fluoride-bornhaber-cycle-and-solution-enthalpies-5.1-sq-medium-q2">Example 5 · Lithium fluoride Born–Haber cycle and solution enthalpies · 5.1 SQ Medium Q2</h3>
<p>One use of pure crystals of lithium fluoride is in X-ray monochromators.</p>
<p><strong>(a)</strong> The Born–Haber cycle for lithium fluoride is shown in Fig. 2.1.</p>
<p><img src="../assets/questions/chemical-energetics/lif-born-haber-cycle.webp" class="question-figure img-fluid" alt="Born-Haber cycle for lithium fluoride with dotted lines to complete"></p>
<p><strong>(i)</strong> Define the term enthalpy of atomisation. <code>[1]</code></p>
<p><strong>(ii)</strong> Explain why the enthalpy of atomisation of fluorine is positive. <code>[1]</code></p>
<p><strong>(iii)</strong> Complete the Born–Haber cycle for lithium fluoride in Fig. 2.1 by adding the missing species on the lines. <code>[2]</code></p>
<p><code>[4 marks]</code></p>
<p><strong>(b)</strong> Use the data in Table 2.1 and your completed Born–Haber cycle from part (a) to answer the questions below.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Name of enthalpy change</th>
<th style="text-align: right;">Energy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathrm{Li(s) \rightarrow Li(g)}\)</span></td>
<td style="text-align: right;">+216</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{Li(g) \rightarrow Li^{+}(g) + e^-}\)</span></td>
<td style="text-align: right;">+520</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{F_2(g) \rightarrow 2F(g)}\)</span></td>
<td style="text-align: right;">+158</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{F(g) + e^- \rightarrow F^{-}(g)}\)</span></td>
<td style="text-align: right;">−348</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{Li(s) + \tfrac{1}{2}F_2(g) \rightarrow LiF(s)}\)</span></td>
<td style="text-align: right;">−594</td>
</tr>
</tbody>
</table>
<p><strong>(i)</strong> Calculate the enthalpy of lattice formation of lithium fluoride. <code>[2]</code></p>
<p><strong>(ii)</strong> Explain and justify how the enthalpy of lattice formation of LiBr compares with that of LiF. You must refer to the size of the ions in your answer. <code>[3]</code></p>
<p><code>[5 marks]</code></p>
<p><strong>(c)</strong> This question is about enthalpy changes in solution.</p>
<p><strong>(i)</strong> Write the equation for the process showing the enthalpy of solution of potassium fluoride. Include state symbols in your answer. <code>[1]</code></p>
<p><strong>(ii)</strong> Use the data in Table 2.2 to calculate the standard enthalpy of solution of potassium fluoride. <code>[2]</code></p>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Name of enthalpy change in solution</th>
<th style="text-align: right;">Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Enthalpy of lattice dissociation of potassium fluoride</td>
<td style="text-align: right;">+829</td>
</tr>
<tr class="even">
<td>Enthalpy of hydration of potassium ions</td>
<td style="text-align: right;">−340</td>
</tr>
<tr class="odd">
<td>Enthalpy of hydration of fluoride ions</td>
<td style="text-align: right;">−504</td>
</tr>
</tbody>
</table>
<p><code>[3 marks]</code></p>
<p><strong>(d)</strong> Explain why the value for the enthalpy of hydration, <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span>, of Group 1 ions increases from lithium to caesium. <code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)(i)</strong> The enthalpy change when one mole of gaseous atoms is formed from its elements under standard conditions. <code>[1]</code></li>
<li><strong>(a)(ii)</strong> Energy is always required to break any bonds between the atoms in the element. <code>[1]</code></li>
<li><strong>(a)(iii)</strong> Atomisation of Li: <span class="math inline">\(\mathrm{Li(g) + \tfrac{1}{2}F_2(g)}\)</span> written on the correct line <code>[1]</code>; first ionisation of Li: <span class="math inline">\(\mathrm{Li^{+}(g) + e^- + \tfrac{1}{2}F_2(g)}\)</span> written on the correct line. <code>[1]</code></li>
<li><strong>(b)(i)</strong> <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}(LiF) = -594 - [216 + 79 + 520 + (-348)]\)</span> (79 = half of +158, one mole of F atoms) <code>[1]</code> <span class="math inline">\(= -1061\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(b)(ii)</strong> LiBr enthalpy of lattice formation is less negative / less exothermic <code>[1]</code>; Br⁻ is bigger (than F⁻) / has more electron shells <code>[1]</code>; so the attraction of bromide ion to lithium ion is weaker. <code>[1]</code></li>
<li><strong>(c)(i)</strong> <span class="math inline">\(\mathrm{KF(s) \rightarrow K^{+}(aq) + F^{-}(aq)}\)</span>. <code>[1]</code></li>
<li><strong>(c)(ii)</strong> <span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}} = (+829) + (-340) + (-504)\)</span> <code>[1]</code> <span class="math inline">\(= -15\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(d)</strong> Ionic radius increases down the group <code>[1]</code>; therefore the attraction between the larger ion and the <span class="math inline">\(\delta^-\)</span> O atoms in the water molecule decreases. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-6-calcium-chloride-lattice-energy-and-calcium-malonate-5.1-sq-medium-q3" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-6-calcium-chloride-lattice-energy-and-calcium-malonate-5.1-sq-medium-q3">Example 6 · Calcium chloride lattice energy and calcium malonate · 5.1 SQ Medium Q3</h3>
<p>Calcium chloride, <span class="math inline">\(\mathrm{CaCl_2}\)</span>, is an important industrial chemical used in refrigeration plants, for de-icing roads and for giving greater strength to concrete.</p>
<p><strong>(a)</strong> Use an equation to show what is meant by the lattice energy of calcium chloride. <code>[1 mark]</code></p>
<p><strong>(b)</strong> Explain how the lattice energies of the following salts compare in magnitude with that of calcium chloride:</p>
<ul>
<li>calcium fluoride;</li>
<li>calcium sulfide.</li>
</ul>
<p><code>[3 marks]</code></p>
<p><strong>(c)</strong> Use the data in Table 3.1 to calculate the lattice energy of <span class="math inline">\(\mathrm{CaCl_2}\)</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Enthalpy change</th>
<th style="text-align: right;">Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard enthalpy change of formation</td>
<td style="text-align: right;">−796</td>
</tr>
<tr class="even">
<td>Standard enthalpy change of atomisation of <span class="math inline">\(\mathrm{Ca(s)}\)</span></td>
<td style="text-align: right;">+178</td>
</tr>
<tr class="odd">
<td>Electron affinity per mole of chlorine atoms</td>
<td style="text-align: right;">−349</td>
</tr>
<tr class="even">
<td>First ionisation energy of Ca</td>
<td style="text-align: right;">+590</td>
</tr>
<tr class="odd">
<td>Second ionisation energy of Ca</td>
<td style="text-align: right;">+1150</td>
</tr>
<tr class="even">
<td>Standard enthalpy change of atomisation of <span class="math inline">\(\mathrm{Cl_2(g)}\)</span></td>
<td style="text-align: right;">+244</td>
</tr>
</tbody>
</table>
<p><code>[3 marks]</code></p>
<p><strong>(d)</strong> When a solution of <span class="math inline">\(\mathrm{CaCl_2}\)</span> is added to a solution of the dicarboxylic acid, malonic acid, the salt calcium malonate is precipitated as a white solid. The solid has the following composition by mass: Ca, 28.2%; C, 25.2%; H, 1.4%; O, 45.2%.</p>
<p><strong>(i)</strong> Calculate the empirical formula of calcium malonate. <code>[2]</code></p>
<p><strong>(ii)</strong> Suggest the structural formula of malonic acid. <code>[1]</code></p>
<p><code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\mathrm{Ca^{2+}(g) + 2Cl^{-}(g) \rightarrow CaCl_2(s)}\)</span>. <code>[1]</code></li>
<li><strong>(b)</strong> Both have larger (more exothermic) lattice enthalpies than <span class="math inline">\(\mathrm{CaCl_2}\)</span> <code>[1]</code>; F⁻ is smaller than Cl⁻ <code>[1]</code>; S²⁻ is more highly charged than Cl⁻. <code>[1]</code></li>
<li><strong>(c)</strong> Lattice energy <span class="math inline">\(= -796 - (178 + 244 + 590 + 1150 + 2 \times (-349))\)</span> <code>[1]</code> <span class="math inline">\(= -2260\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[1]</code>; the answer must be negative. <code>[1]</code></li>
<li><strong>(d)(i)</strong> Moles: Ca <span class="math inline">\(28.2/40.1 = 0.703\)</span>; C <span class="math inline">\(25.2/12.0 = 2.10\)</span>; H <span class="math inline">\(1.4/1.0 = 1.4\)</span>; O <span class="math inline">\(45.2/16.0 = 2.83\)</span>; divide by 0.703 gives the ratio CaC₃H₂O₄ <code>[2]</code>.</li>
<li><strong>(d)(ii)</strong> <span class="math inline">\(\mathrm{CH_2(CO_2H)_2}\)</span>. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-7-hydration-enthalpy-and-the-experimental-determination-of-delta-h_mathrmsol-5.1-sq-medium-q4" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-7-hydration-enthalpy-and-the-experimental-determination-of-delta-h_mathrmsol-5.1-sq-medium-q4">Example 7 · Hydration enthalpy and the experimental determination of <span class="math inline">\(\Delta H_{\mathrm{sol}}\)</span> · 5.1 SQ Medium Q4</h3>
<p>This question is about enthalpy change of hydration.</p>
<p><strong>(a)</strong> Explain what is meant by the term enthalpy change of hydration, <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span>. <code>[1 mark]</code></p>
<p><strong>(b)</strong></p>
<p><strong>(i)</strong> Write an equation that represents the <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span> of the <span class="math inline">\(\mathrm{Mg^{2+}}\)</span> ions. <code>[1]</code></p>
<p><strong>(ii)</strong> Suggest a reason why the <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span> of the <span class="math inline">\(\mathrm{Mg^{2+}}\)</span> ion is greater than <span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}\)</span> of the <span class="math inline">\(\mathrm{Ca^{2+}}\)</span> ion. <code>[1]</code></p>
<p><code>[2 marks]</code></p>
<p><strong>(c)</strong> The enthalpy change of solution for <span class="math inline">\(\mathrm{MgCl_2}\)</span>, (<span class="math inline">\(\mathrm{MgCl_2(s)}\)</span>), is represented by the following equation:</p>
<p><span class="math display">\[\mathrm{MgCl_2(s) + aq \rightarrow Mg^{2+}(aq) + 2Cl^{-}(aq)}\]</span></p>
<p>Describe the simple apparatus you could use, and the measurements you would make, in order to determine a value for <span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}}(\mathrm{MgCl_2(s)})\)</span> in the laboratory. <code>[4 marks]</code></p>
<p><strong>(d)</strong> Use the data in Table 4.1 to calculate the value for the enthalpy change of solution for magnesium chloride.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Enthalpy change</th>
<th style="text-align: right;">Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span> <span class="math inline">\(\mathrm{MgCl_2(s)}\)</span></td>
<td style="text-align: right;">−2526</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}(\mathrm{Mg^{2+}(g)})\)</span></td>
<td style="text-align: right;">−1890</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_{\mathrm{hyd}}(\mathrm{Cl^{-}(g)})\)</span></td>
<td style="text-align: right;">−398</td>
</tr>
</tbody>
</table>
<p><code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> The enthalpy change when 1 mole of gaseous ions dissolves in water. <code>[1]</code></li>
<li><strong>(b)(i)</strong> <span class="math inline">\(\mathrm{Mg^{2+}(g) + aq \rightarrow Mg^{2+}(aq)}\)</span> (or <span class="math inline">\(\mathrm{Mg^{2+}(g) + 6H_2O \rightarrow [Mg(H_2O)_6]^{2+}}\)</span>). <code>[1]</code></li>
<li><strong>(b)(ii)</strong> <span class="math inline">\(\mathrm{Mg^{2+}}\)</span> has a smaller radius / size compared to <span class="math inline">\(\mathrm{Ca^{2+}}\)</span>, or a greater charge density. <code>[1]</code></li>
<li><strong>(c)</strong> Measure a known volume / mass of water into a calorimeter <code>[1]</code>; take the temperature of the water <code>[1]</code>; weigh out a known mass of <span class="math inline">\(\mathrm{MgCl_2}\)</span> <code>[1]</code>; take the final / highest temperature, or record the temperature change. <code>[1]</code></li>
<li><strong>(d)</strong> <span class="math inline">\(\Delta H^\ominus_{\mathrm{sol}} = \Delta H^\ominus_{\mathrm{hyd}}(Mg^{2+}) + 2 \times \Delta H^\ominus_{\mathrm{hyd}}(Cl^-) - \Delta H^\ominus_{\mathrm{latt}}\)</span> <code>[1]</code> <span class="math inline">\(= (-1890) + 2 \times (-398) - (-2526)\)</span> <code>[1]</code> <span class="math inline">\(= -160\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-8-electron-affinity-and-the-electron-affinity-of-fluorine-5.1-sq-medium-q5" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-8-electron-affinity-and-the-electron-affinity-of-fluorine-5.1-sq-medium-q5">Example 8 · Electron affinity and the electron affinity of fluorine · 5.1 SQ Medium Q5</h3>
<p>Magnesium reacts with fluorine to form magnesium fluoride.</p>
<p><strong>(a)</strong> Explain what is meant by the term first electron affinity. <code>[2 marks]</code></p>
<p><strong>(b)</strong></p>
<p><strong>(i)</strong> Write an equation for the second electron affinity of fluorine. <code>[1]</code></p>
<p><strong>(ii)</strong> Suggest why the second electron affinity for fluorine is endothermic. <code>[1]</code></p>
<p><code>[2 marks]</code></p>
<p><strong>(c)</strong> Determine the electron affinity of a fluorine atom, <span class="math inline">\(\Delta H^\ominus_{ea}\)</span>, using Table 5.1.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Name of enthalpy change</th>
<th style="text-align: right;">Energy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Enthalpy of atomisation of magnesium</td>
<td style="text-align: right;">+150</td>
</tr>
<tr class="even">
<td>Second ionisation energy of magnesium</td>
<td style="text-align: right;">+1450</td>
</tr>
<tr class="odd">
<td>Enthalpy of formation of magnesium fluoride</td>
<td style="text-align: right;">−642</td>
</tr>
<tr class="even">
<td>Lattice enthalpy of formation of magnesium fluoride</td>
<td style="text-align: right;">−2493</td>
</tr>
</tbody>
</table>
<p><code>[3 marks]</code></p>
<p><strong>(d)</strong> Explain the trend in the first electron affinities going from fluorine to iodine. <code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> The enthalpy change when 1 mole of electrons is added <code>[1]</code> to 1 mole of gaseous atoms to form 1 mole of gaseous ions with a single negative charge, under standard conditions. <code>[1]</code></li>
<li><strong>(b)(i)</strong> <span class="math inline">\(\mathrm{F^{-}(g) + e^- \rightarrow F^{2-}(g)}\)</span>. <code>[1]</code></li>
<li><strong>(b)(ii)</strong> Energy is needed to add electrons to the already negative ion / to overcome repulsion. <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(2\Delta H^\ominus_{ea}(F) = \Delta H^\ominus_f(MgF_2) - \Delta H^\ominus_{at}(Mg) - \Delta H^\ominus_{ie1}(Mg) - \Delta H^\ominus_{ie2}(Mg) - 2\Delta H^\ominus_{at}(F) - \Delta H^\ominus_{latt}(MgF_2)\)</span> <code>[1]</code> <span class="math inline">\(= -642 - 150 - 738 - 1450 - 159 - (-2493) = -646\)</span> <code>[1]</code>, so <span class="math inline">\(\Delta H^\ominus_{ea}(F) = -323\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(d)</strong> (Electron affinity) decreases <code>[1]</code>; there is more shielding by inner electrons and the number of shells / ionic radius increases <code>[1]</code>; so there is less attraction between the electron being gained and the positively charged nucleus. <code>[1]</code></li>
</ul>
</details>
</section>
<div class="small-note">
<p><strong>Source check:</strong> the printed Table 5.1 in the question paper shows only four rows; the model answer also uses <span class="math inline">\(\Delta H^\ominus_{ie1}(Mg) = +738\ \mathrm{kJ\,mol^{-1}}\)</span> and atomisation of fluorine <span class="math inline">\(2\Delta H^\ominus_{at}(F) = +159\ \mathrm{kJ\,mol^{-1}}\)</span>, which are missing from the printed table.</p>
</div>
<section id="chemical-energetics---hard" class="level3">
<h3 class="anchored" data-anchor-id="chemical-energetics---hard">5.1 Chemical Energetics - Hard</h3>
</section>
<section id="example-9-drawing-the-k₂s-bornhaber-cycle-and-calculating-lattice-enthalpy-5.1-sq-hard-q1" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-9-drawing-the-k₂s-bornhaber-cycle-and-calculating-lattice-enthalpy-5.1-sq-hard-q1">Example 9 · Drawing the K₂S Born–Haber cycle and calculating lattice enthalpy · 5.1 SQ Hard Q1</h3>
<p>Potassium sulfide is a reagent used in analytical chemistry and pharmaceutical preparations.</p>
<p><strong>(a)</strong> Draw a fully labelled Born–Haber cycle for the formation of solid potassium sulfide from its elements. Include state symbols for all species involved. <code>[7 marks]</code></p>
<p><strong>(b)</strong> Use the data in Table 1.1 to calculate the lattice enthalpy of potassium sulfide, <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span>. Show your working.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Enthalpy change</th>
<th style="text-align: right;">Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Formation of potassium sulfide</td>
<td style="text-align: right;">−381</td>
</tr>
<tr class="even">
<td>1st electron affinity of sulfur</td>
<td style="text-align: right;">−200</td>
</tr>
<tr class="odd">
<td>2nd electron affinity of sulfur</td>
<td style="text-align: right;">+640</td>
</tr>
<tr class="even">
<td>Atomisation of sulfur</td>
<td style="text-align: right;">+279</td>
</tr>
<tr class="odd">
<td>1st ionisation energy of potassium</td>
<td style="text-align: right;">+419</td>
</tr>
<tr class="even">
<td>Atomisation of potassium</td>
<td style="text-align: right;">+89</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}} = \underline{\hspace{6em}}\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[3 marks]</code></p>
<p><strong>(c)</strong> Explain the difference in values between the first and second electron affinities of sulfur. <code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> The cycle must show, on the correct energy levels:
<ul>
<li><span class="math inline">\(\Delta H^\ominus_f\)</span> (K₂S) and <span class="math inline">\(2K(s) + S(s)\)</span> <code>[1]</code>;</li>
<li><span class="math inline">\(\Delta H^\ominus_{at}\)</span> (S) and <span class="math inline">\(2K(s) + S(g)\)</span> <code>[1]</code>;</li>
<li><span class="math inline">\(2\Delta H^\ominus_{at}\)</span> (K) and <span class="math inline">\(2K(g) + S(g)\)</span> <code>[1]</code>;</li>
<li><span class="math inline">\(2IE_1\)</span> (K) and <span class="math inline">\(2K^{+}(g) + S(g) + 2e^-\)</span> <code>[1]</code>;</li>
<li><span class="math inline">\(EA_1\)</span> (S) and <span class="math inline">\(2K^{+}(g) + S^{-}(g) + e^-\)</span> <code>[1]</code>;</li>
<li><span class="math inline">\(EA_2\)</span> (S) and <span class="math inline">\(2K^{+}(g) + S^{2-}(g)\)</span> <code>[1]</code>;</li>
<li><span class="math inline">\(\mathrm{K_2S(s)}\)</span> and <span class="math inline">\(\Delta H^\ominus_{latt}\)</span> (downward arrow). <code>[1]</code></li>
</ul></li>
<li><strong>(b)</strong> <span class="math inline">\(\Delta H^\ominus_{latt} = \Delta H^\ominus_f - [\Delta H^\ominus_{at}(S) + 2\Delta H^\ominus_{at}(K) + 2\Delta H^\ominus_{ie}(K) + EA_1(S) + EA_2(S)]\)</span> <code>[1]</code> <span class="math inline">\(= -381 - (279 + 178 + 838 - 200 + 640)\)</span> <code>[1]</code> <span class="math inline">\(= -2116\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(c)</strong> The first electron affinity is exothermic and the second is endothermic <code>[1]</code>; because there is repulsion between the negative ion and the incoming negative electron. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-10-magnesium-oxide-and-the-second-ionisation-energy-of-magnesium-5.1-sq-hard-q2" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-10-magnesium-oxide-and-the-second-ionisation-energy-of-magnesium-5.1-sq-hard-q2">Example 10 · Magnesium oxide and the second ionisation energy of magnesium · 5.1 SQ Hard Q2</h3>
<p>Magnesium oxide is often used in optical applications due to its light-reflecting properties in crystal form.</p>
<p><strong>(a)</strong> Write an equation to represent the lattice energy of <span class="math inline">\(\mathrm{MgO}\)</span>. <code>[1 mark]</code></p>
<p><strong>(b)</strong> Use the data in Table 2.1 to calculate a value for the second ionisation energy of magnesium, <span class="math inline">\(\Delta H^\ominus_{ie2}\)</span>. Show your working.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Enthalpy change</th>
<th style="text-align: right;">Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lattice energy of <span class="math inline">\(\mathrm{MgO(s)}\)</span></td>
<td style="text-align: right;">−3791</td>
</tr>
<tr class="even">
<td>Enthalpy change of atomisation of Mg</td>
<td style="text-align: right;">+148</td>
</tr>
<tr class="odd">
<td>Enthalpy of atomisation of oxygen</td>
<td style="text-align: right;">+248</td>
</tr>
<tr class="even">
<td>Electron affinity of the oxygen atom</td>
<td style="text-align: right;">−141</td>
</tr>
<tr class="odd">
<td>Electron affinity of the oxygen anion, O⁻</td>
<td style="text-align: right;">+798</td>
</tr>
<tr class="even">
<td>First ionisation energy of Mg</td>
<td style="text-align: right;">+736</td>
</tr>
<tr class="odd">
<td>Enthalpy of formation of MgO</td>
<td style="text-align: right;">−552</td>
</tr>
</tbody>
</table>
<p>Second ionisation energy of Mg <span class="math inline">\(= \underline{\hspace{6em}}\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[3 marks]</code></p>
<p><strong>(c)</strong> Magnesium oxide is generally insoluble in water whereas calcium oxide is sparingly soluble. Explain why there is no enthalpy of solution data for calcium oxide. <code>[1 mark]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\mathrm{Mg^{2+}(g) + O^{2-}(g) \rightarrow MgO(s)}\)</span>. <code>[1]</code></li>
<li><strong>(b)</strong> <span class="math inline">\(\Delta H^\ominus_{ie2}(Mg) = \Delta H^\ominus_f(MgO) - [\Delta H^\ominus_{at}(Mg) + \Delta H^\ominus_{ie1}(Mg) + \Delta H^\ominus_{at}(O) + EA_1(O) + EA_2(O) + \Delta H^\ominus_{latt}(MgO)]\)</span> <code>[1]</code> <span class="math inline">\(= -552 - (148 + 736 + 248 - 141 + 798 - 3791)\)</span> <code>[1]</code> <span class="math inline">\(= +1450\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(c)</strong> Calcium oxide reacts with water to produce OH⁻ ions in solution. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-11-sodium-selenide-cycle-and-the-lattice-energy-of-aluminium-oxide-5.1-sq-hard-q3" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-11-sodium-selenide-cycle-and-the-lattice-energy-of-aluminium-oxide-5.1-sq-hard-q3">Example 11 · Sodium selenide cycle and the lattice energy of aluminium oxide · 5.1 SQ Hard Q3</h3>
<p><strong>(a)</strong> The incomplete Born–Haber cycle for sodium selenide is shown in Fig. 3.1.</p>
<p><img src="../assets/questions/chemical-energetics/na2se-born-haber-cycle.webp" class="question-figure img-fluid" alt="Incomplete Born-Haber cycle for sodium selenide with processes 1, 2 and 3 to complete"></p>
<p>Write the equations for processes 1, 2 and 3. <code>[3 marks]</code></p>
<p><strong>(b)</strong> If sulfur is used as opposed to selenium in the lattice, suggest the change in value of the lattice energy, <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span>. Explain your answer. <code>[3 marks]</code></p>
<p><strong>(c)</strong> Use the data in Table 3.1 to calculate the lattice energy of aluminium oxide, <span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}\)</span>. Show your working.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Enthalpy change</th>
<th style="text-align: right;">Enthalpy change / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Atomisation of aluminium</td>
<td style="text-align: right;">+326</td>
</tr>
<tr class="even">
<td>Atomisation of oxygen</td>
<td style="text-align: right;">+249</td>
</tr>
<tr class="odd">
<td>First ionisation energy of aluminium</td>
<td style="text-align: right;">+578</td>
</tr>
<tr class="even">
<td>Second ionisation energy of aluminium</td>
<td style="text-align: right;">+1817</td>
</tr>
<tr class="odd">
<td>Third ionisation energy of aluminium</td>
<td style="text-align: right;">+2745</td>
</tr>
<tr class="even">
<td>Electron affinity of O atom</td>
<td style="text-align: right;">−141</td>
</tr>
<tr class="odd">
<td>Electron affinity of O⁻</td>
<td style="text-align: right;">+753</td>
</tr>
<tr class="even">
<td>Formation of aluminium oxide</td>
<td style="text-align: right;">−1670</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\Delta H^\ominus_{\mathrm{latt}}(\mathrm{Al_2O_3}) = \underline{\hspace{6em}}\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> 1: <span class="math inline">\(2\mathrm{Na(s) + Se(s)}\)</span> <code>[1]</code>; 2: <span class="math inline">\(2\mathrm{Na(g) + Se(g)}\)</span> <code>[1]</code>; 3: <span class="math inline">\(2\mathrm{Na(g) + Se(g) \rightarrow 2Na^{+}(g) + Se(g) + 2e^-}\)</span> (first ionisation of both Na atoms). <code>[1]</code></li>
<li><strong>(b)</strong> Become more negative / more exothermic <code>[1]</code>; the S²⁻ ion is smaller than the Se²⁻ ion / has fewer electron shells <code>[1]</code>; so the attraction between Na⁺ and S²⁻ is stronger. <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(\Delta H^\ominus_{latt} = \Delta H^\ominus_f - [2\Delta H^\ominus_{at}(Al) + 3\Delta H^\ominus_{at}(O) + 2IE_1(Al) + 2IE_2(Al) + 2IE_3(Al) + 3EA_1(O) + 3EA_2(O)]\)</span> <code>[1]</code> <span class="math inline">\(= -1670 - [652 + 747 + 1156 + 3634 + 5490 - 423 + 2259]\)</span> <code>[1]</code> <span class="math inline">\(= -15185\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-12-identifying-a-group-1-ion-from-solution-data-5.1-sq-hard-q4" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-12-identifying-a-group-1-ion-from-solution-data-5.1-sq-hard-q4">Example 12 · Identifying a Group 1 ion from solution data · 5.1 SQ Hard Q4</h3>
<p>A Group 1 metal, M, formed an ionic compound with chlorine.</p>
<p>The enthalpy of lattice dissociation for this compound is <span class="math inline">\(+773\ \mathrm{kJ\,mol^{-1}}\)</span> and the hydration enthalpy of a chloride ion is <span class="math inline">\(-363\ \mathrm{kJ\,mol^{-1}}\)</span>.</p>
<p>The enthalpy of solution of the Group 1 chloride is <span class="math inline">\(+4\ \mathrm{kJ\,mol^{-1}}\)</span>.</p>
<p><strong>(a)</strong> Using the information in Table 4.1, identify the Group 1 ion, M⁺. Show your working.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group 1 ion</th>
<th style="text-align: right;">Enthalpy of hydration / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Li⁺</td>
<td style="text-align: right;">−519</td>
</tr>
<tr class="even">
<td>Na⁺</td>
<td style="text-align: right;">−406</td>
</tr>
<tr class="odd">
<td>K⁺</td>
<td style="text-align: right;">−321</td>
</tr>
<tr class="even">
<td>Rb⁺</td>
<td style="text-align: right;">−296</td>
</tr>
</tbody>
</table>
<p>Identity of M⁺ = <span class="math inline">\(\underline{\hspace{5em}}\)</span> <code>[2 marks]</code></p>
<p><strong>(b)</strong> The same Group 1 metal from part (a) forms an ionic lattice with another halide ion. This new ionic compound has an enthalpy of lattice formation of <span class="math inline">\(-705\ \mathrm{kJ\,mol^{-1}}\)</span>.</p>
<p>Using M to represent the Group 1 metal, suggest a formula for the new ionic lattice and explain your answer. <code>[4 marks]</code></p>
<p><strong>(c)</strong> The enthalpy of hydration becomes less exothermic as you go down Group 1. Using the values in part (a):</p>
<p><strong>(i)</strong> Explain why the enthalpy of hydration of Group 1 ions is negative. <code>[3]</code></p>
<p><strong>(ii)</strong> Explain why the enthalpies of hydration become less negative as you go down the group. <code>[2]</code></p>
<p><code>[5 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\Delta H^\ominus_{sol} = \Delta H^\ominus_{latt}(dissociation) + \Sigma \Delta H^\ominus_{hyd}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta H^\ominus_{hyd}(M^+) = 4 - 773 - (-363) = -406\ \mathrm{kJ\,mol^{-1}}\)</span>, which matches Na⁺. <code>[1]</code></li>
<li><strong>(b)</strong> MBr(s) or MI(s) <code>[1]</code>; the new ionic lattice has a less negative (less exothermic) lattice enthalpy <code>[1]</code>; so the new halide ion must be bigger than Cl⁻ / have more electron shells <code>[1]</code>; the attraction between M⁺ and the new halide ion is weaker. <code>[1]</code></li>
<li><strong>(c)(i)</strong> Water is polar / the oxygen in water has <span class="math inline">\(\delta^-\)</span> charges <code>[1]</code>; Group 1 ions attract the <span class="math inline">\(\delta^-\)</span> oxygen <code>[1]</code>; bonds are formed between the ions and polar water molecules. <code>[1]</code></li>
<li><strong>(c)(ii)</strong> The size of the ions increases down the group / more electron shells <code>[1]</code>; the attraction between the positive Group 1 ion and the <span class="math inline">\(\delta^-\)</span> oxygen decreases down the group. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="entropy---easy" class="level3">
<h3 class="anchored" data-anchor-id="entropy---easy">5.2 Entropy - Easy</h3>
</section>
<section id="example-13-the-gibbs-equation-delta-s-and-minimum-temperature-5.2-sq-easy-q1" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-13-the-gibbs-equation-delta-s-and-minimum-temperature-5.2-sq-easy-q1">Example 13 · The Gibbs equation, <span class="math inline">\(\Delta S\)</span> and minimum temperature · 5.2 SQ Easy Q1</h3>
<p>The feasibility of a reaction is determined by the relationship between enthalpy change and entropy change.</p>
<p><strong>(a)</strong> Write the equation that shows the relationship between <span class="math inline">\(\Delta G\)</span>, <span class="math inline">\(\Delta H\)</span> and <span class="math inline">\(\Delta S\)</span>. <code>[1 mark]</code></p>
<p><strong>(b)</strong> What is the requirement for a reaction to be feasible? <code>[1 mark]</code></p>
<p><strong>(c)</strong> Chlorine can be formed in the following reversible reaction:</p>
<p><span class="math display">\[\mathrm{4HCl(g) + O_2(g) \rightleftharpoons 2Cl_2(g) + 2H_2O(g)}\]</span></p>
<p>Use the following data to calculate the standard entropy change, <span class="math inline">\(\Delta S^\ominus\)</span>, for this reaction.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">HCl(g)</th>
<th style="text-align: right;">O₂(g)</th>
<th style="text-align: right;">Cl₂(g)</th>
<th style="text-align: right;">H₂O(g)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(S^\ominus\)</span> / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></td>
<td style="text-align: right;">187</td>
<td style="text-align: right;">205</td>
<td style="text-align: right;">223</td>
<td style="text-align: right;">189</td>
</tr>
</tbody>
</table>
<p>The equation to calculate standard entropy change is:</p>
<p><span class="math display">\[\Delta S^\ominus = \Sigma\, S^\ominus_{products} - \Sigma\, S^\ominus_{reactants}\]</span></p>
<p><code>[3 marks]</code></p>
<p><strong>(d)</strong> The standard enthalpy change for the reaction in (c) is <span class="math inline">\(-116\ \mathrm{kJ\,mol^{-1}}\)</span>.</p>
<p>Calculate the minimum temperature at which this reaction is feasible. <code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\Delta G = \Delta H - T\Delta S\)</span> (equivalently <span class="math inline">\(\Delta H = \Delta G + T\Delta S\)</span>). <code>[1]</code></li>
<li><strong>(b)</strong> <span class="math inline">\(\Delta G\)</span> is less than or equal to zero (<span class="math inline">\(\Delta G \leq 0\)</span>). <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(\Delta S^\ominus = (2 \times 223 + 2 \times 189) - (205 + 4 \times 187)\)</span> <code>[1]</code> <span class="math inline">\(= 824 - 953\)</span> <code>[1]</code> <span class="math inline">\(= -129\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(d)</strong> <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S} = \dfrac{-116 \times 1000}{-129}\)</span> <code>[1]</code> <span class="math inline">\(= 899\ \mathrm{K}\)</span>. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-14-ammonium-chloride-dissociation-and-feasibility-5.2-sq-easy-q2" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-14-ammonium-chloride-dissociation-and-feasibility-5.2-sq-easy-q2">Example 14 · Ammonium chloride dissociation and feasibility · 5.2 SQ Easy Q2</h3>
<p>Ammonium chloride, <span class="math inline">\(\mathrm{NH_4Cl}\)</span>, can dissociate to form ammonia, <span class="math inline">\(\mathrm{NH_3}\)</span>, and hydrogen chloride, HCl.</p>
<p><span class="math display">\[\mathrm{NH_4Cl(s) \rightarrow NH_3(g) + HCl(g)}\]</span></p>
<p><strong>(a)</strong> Explain whether entropy increases or decreases in this reaction. <code>[3 marks]</code></p>
<p><strong>(b)</strong> At 298 K, <span class="math inline">\(\Delta H = +176\ \mathrm{kJ\,mol^{-1}}\)</span> and <span class="math inline">\(\Delta S = +285\ \mathrm{J\,mol^{-1}\,K^{-1}}\)</span>.</p>
<p>Calculate <span class="math inline">\(\Delta G\)</span> for this reaction at 298 K. <code>[3 marks]</code></p>
<p><strong>(c)</strong> Explain whether the reaction is feasible under standard conditions. <code>[2 marks]</code></p>
<p><strong>(d)</strong> State and explain how the feasibility of the reaction will change with increasing temperature. <code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> Entropy increases <code>[1]</code>; a gas is formed from a solid <code>[1]</code>; gases are more disordered / random / chaotic. <code>[1]</code></li>
<li><strong>(b)</strong> Convert <span class="math inline">\(\Delta S\)</span>: <span class="math inline">\(285/1000 = 0.285\ \mathrm{kJ\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta G = (+176) - (298 \times 0.285)\)</span> <code>[1]</code> <span class="math inline">\(= +91.1\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(c)</strong> Not feasible <code>[1]</code>; (because) <span class="math inline">\(\Delta G^\ominus\)</span> is positive. <code>[1]</code></li>
<li><strong>(d)</strong> Feasibility increases / the reaction becomes (more) feasible <code>[1]</code>; (because) <span class="math inline">\(\Delta G\)</span> will decrease (as <span class="math inline">\(T\Delta S\)</span> grows). <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-15-melting-of-ice-5.2-sq-easy-q3" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-15-melting-of-ice-5.2-sq-easy-q3">Example 15 · Melting of ice · 5.2 SQ Easy Q3</h3>
<p>The following equation represents the melting of ice:</p>
<p><span class="math display">\[\mathrm{H_2O(s) \rightarrow H_2O(l)} \qquad \Delta H^\ominus = +6.03\ \mathrm{kJ\,mol^{-1}}, \quad \Delta S^\ominus = +22.1\ \mathrm{J\,K^{-1}\,mol^{-1}}\]</span></p>
<p><strong>(a)</strong> State the meaning of the symbol <span class="math inline">\(\ominus\)</span> in <span class="math inline">\(\Delta H^\ominus\)</span>. <code>[1 mark]</code></p>
<p><strong>(b)</strong> Explain whether the entropy of the system increases or decreases. <code>[3 marks]</code></p>
<p><strong>(c)</strong> Calculate the temperature at which <span class="math inline">\(\Delta G^\ominus = 0\)</span> for this process. Show your working. <code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> Standard conditions (101 kPa, 298 K). <code>[1]</code></li>
<li><strong>(b)</strong> Entropy increases <code>[1]</code>; because a liquid is formed <code>[1]</code>; (liquids are) more disordered / chaotic (than solids). <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S} = \dfrac{6.03 \times 1000}{22.1}\)</span> <code>[1+1]</code> <span class="math inline">\(= 273\ \mathrm{K}\)</span>. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="entropy---medium" class="level3">
<h3 class="anchored" data-anchor-id="entropy---medium">5.2 Entropy - Medium</h3>
</section>
<section id="example-16-entropy-changes-and-the-decomposition-of-calcium-carbonate-5.2-sq-medium-q1" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-16-entropy-changes-and-the-decomposition-of-calcium-carbonate-5.2-sq-medium-q1">Example 16 · Entropy changes and the decomposition of calcium carbonate · 5.2 SQ Medium Q1</h3>
<p>The spontaneity of a chemical reaction depends on the standard Gibbs free energy change, <span class="math inline">\(\Delta G^\ominus\)</span>.</p>
<p><strong>(a)</strong> State and explain whether the following processes will lead to an increase or decrease in entropy.</p>
<p><strong>(i)</strong> Steam condensing to water <code>[1]</code></p>
<p><strong>(ii)</strong> Zinc reacting with nitric acid <code>[1]</code></p>
<p><strong>(iii)</strong> Sodium chloride dissolving in water <code>[1]</code></p>
<p><code>[3 marks]</code></p>
<p><strong>(b)</strong> Calcium carbonate thermally decomposes to form calcium oxide and carbon dioxide, as shown below:</p>
<p><span class="math display">\[\mathrm{CaCO_3(s) \rightarrow CaO(s) + CO_2(g)}\]</span></p>
<p>The enthalpy change of the above reaction is <span class="math inline">\(\Delta H^\ominus = +178\ \mathrm{kJ\,mol^{-1}}\)</span>.</p>
<p>Standard entropies are shown in Table 1.1.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Substance</th>
<th style="text-align: right;">CaCO₃(s)</th>
<th style="text-align: right;">CaO(s)</th>
<th style="text-align: right;">CO₂(g)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(S^\ominus\)</span> / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></td>
<td style="text-align: right;">+92.9</td>
<td style="text-align: right;">+39.8</td>
<td style="text-align: right;">+214</td>
</tr>
</tbody>
</table>
<p>Calculate the free energy change, <span class="math inline">\(\Delta G^\ominus\)</span>, at 298 K for this process. Include the relevant sign and give your answer to three significant figures. Show your working. <code>[3 marks]</code></p>
<p><strong>(c)</strong> Explain, with reference to <span class="math inline">\(\Delta G^\ominus\)</span>, why this reaction becomes more feasible at higher temperatures. <code>[1 mark]</code></p>
<p><strong>(d)</strong> On heating, sodium hydrogencarbonate decomposes into sodium carbonate as shown:</p>
<p><span class="math display">\[\mathrm{2NaHCO_3(s) \rightarrow Na_2CO_3(s) + CO_2(g) + H_2O(g)} \qquad \Delta H^\ominus = +130\ \mathrm{kJ\,mol^{-1}}, \quad \Delta S^\ominus = +316\ \mathrm{J\,mol^{-1}\,K^{-1}}\]</span></p>
<p>Calculate the minimum temperature at which the reaction becomes spontaneous. Show your working. <code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)(i)</strong> Decreases / is negative, because a gas turns into a liquid (decrease in gas). <code>[1]</code></li>
<li><strong>(a)(ii)</strong> Increases / is positive, because <span class="math inline">\(\mathrm{H_2}\)</span> gas is formed. <code>[1]</code></li>
<li><strong>(a)(iii)</strong> Increases / is positive, because the NaCl(aq) solution has free-moving / mobile aqueous ions. <code>[1]</code></li>
<li><strong>(b)</strong> <span class="math inline">\(\Delta S^\ominus = (39.8 + 214) - 92.9 = +160.9\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta G^\ominus = 178 - 298 \times 0.1609\)</span> <code>[1]</code> <span class="math inline">\(= +130\ \mathrm{kJ\,mol^{-1}}\)</span> (3 s.f.). <code>[1]</code></li>
<li><strong>(c)</strong> At higher temperatures <span class="math inline">\(T\Delta S^\ominus\)</span> is more positive than <span class="math inline">\(\Delta H^\ominus\)</span> <code>[1]</code>, so <span class="math inline">\(\Delta G^\ominus\)</span> is negative / decreases / becomes less positive.</li>
<li><strong>(d)</strong> <span class="math inline">\(\Delta G^\ominus = \Delta H^\ominus - T\Delta S^\ominus = 0\)</span>, so <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S} = \dfrac{130\,000}{316}\)</span> <code>[1+1]</code> <span class="math inline">\(= 411\ \mathrm{K}\)</span> (410–412 K accepted). <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-17-the-ostwald-process-5.2-sq-medium-q2" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-17-the-ostwald-process-5.2-sq-medium-q2">Example 17 · The Ostwald process · 5.2 SQ Medium Q2</h3>
<p>Ammonia, <span class="math inline">\(\mathrm{NH_3}\)</span>, is produced by the Haber process and is an important chemical in the manufacture of fertilisers and cleaning products.</p>
<p>Ammonia gas can react with oxygen to produce nitrogen monoxide and steam, and is the first step in the Ostwald process which produces nitric acid.</p>
<p><strong>(a)</strong></p>
<p><strong>(i)</strong> Write an equation for the reaction of ammonia with oxygen to produce nitrogen monoxide and steam. <code>[2]</code></p>
<p><strong>(ii)</strong> Table 2.1 shows the entropy values for the species involved in the reaction.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Substance</th>
<th style="text-align: right;">Entropy values / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NH₃(g)</td>
<td style="text-align: right;">192.8</td>
</tr>
<tr class="even">
<td>O₂(g)</td>
<td style="text-align: right;">205.2</td>
</tr>
<tr class="odd">
<td>H₂O(g)</td>
<td style="text-align: right;">188.8</td>
</tr>
<tr class="even">
<td>NO(g)</td>
<td style="text-align: right;">210.8</td>
</tr>
</tbody>
</table>
<p>Use the data in Table 2.1 to determine the entropy change for this reaction at 298 K. <code>[3]</code></p>
<p><code>[5 marks]</code></p>
<p><strong>(b)</strong> Explain why the standard entropy change for the reaction in part (a) is positive. <code>[1 mark]</code></p>
<p><strong>(c)</strong> The second step in the Ostwald process produces nitrogen dioxide as shown in the equation:</p>
<p><span class="math display">\[\mathrm{2NO(g) + O_2(g) \rightarrow 2NO_2(g)} \qquad \Delta H^\ominus = -112\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p>The standard entropy for <span class="math inline">\(\mathrm{NO_2(g)}\)</span> is <span class="math inline">\(240.0\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>.</p>
<p>Use Table 2.1 to determine the value for the free energy change, <span class="math inline">\(\Delta G^\ominus\)</span>, for this reaction at 298 K. Show your working. <code>[6 marks]</code></p>
<p><strong>(d)</strong> Explain whether changing the temperature for the production of nitrogen dioxide will alter the spontaneity of the reaction. <code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)(i)</strong> <span class="math inline">\(\mathrm{4NH_3(g) + 5O_2(g) \rightarrow 4NO(g) + 6H_2O(g)}\)</span>: correct reactants, products and balancing <code>[1]</code>; correct state symbols. <code>[1]</code></li>
<li><strong>(a)(ii)</strong> <span class="math inline">\(\Delta S^\ominus = [(4 \times 210.8) + (6 \times 188.8)] - [(4 \times 192.8) + (5 \times 205.2)]\)</span> <code>[1]</code> <span class="math inline">\(= 1976 - 1797.2\)</span> <code>[1]</code> <span class="math inline">\(= +178.8\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(b)</strong> There are 10 moles of gas in the products and 9 moles of gas in the reactants (more moles of gas in the products). <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(\Delta S^\ominus = (2 \times 240.0) - (2 \times 210.8 + 205.2)\)</span> <code>[1]</code> <span class="math inline">\(= 480 - 626.8 = -146.8\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta G^\ominus = \Delta H^\ominus - T\Delta S^\ominus\)</span> <code>[1]</code> <span class="math inline">\(= -112 - 298 \times (-0.1468)\)</span> <code>[1]</code> <span class="math inline">\(= -68.3\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1+1]</code></li>
<li><strong>(d)</strong> Yes — the spontaneity is dependent on temperature <code>[1]</code>; decreasing the temperature makes <span class="math inline">\(\Delta G^\ominus\)</span> more negative (increasing the temperature makes it more positive). <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-18-potassium-nitrate-dissolving-5.2-sq-medium-q3" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-18-potassium-nitrate-dissolving-5.2-sq-medium-q3">Example 18 · Potassium nitrate dissolving · 5.2 SQ Medium Q3</h3>
<p>Potassium nitrate is a soluble salt. When it dissolves in water the value of the enthalpy change <span class="math inline">\(\Delta H^\ominus = +34.9\ \mathrm{kJ\,mol^{-1}}\)</span> and the value of the entropy change <span class="math inline">\(\Delta S^\ominus = +117\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>.</p>
<p><strong>(a)</strong> Write an equation, including state symbols, for the process that occurs when potassium nitrate dissolves in water. <code>[1 mark]</code></p>
<p><strong>(b)</strong> Explain why <span class="math inline">\(\Delta S^\ominus\)</span> is positive for this process. <code>[1 mark]</code></p>
<p><strong>(c)</strong> Calculate the minimum temperature at which the reaction will become feasible. Show your working. <code>[3 marks]</code></p>
<p><strong>(d)</strong></p>
<p><strong>(i)</strong> Deduce what happens to the value of <span class="math inline">\(\Delta G^\ominus\)</span> when potassium nitrate dissolves in water at a temperature lower than your answer to part (c). <code>[1]</code></p>
<p><strong>(ii)</strong> What does this new value of <span class="math inline">\(\Delta G^\ominus\)</span> suggest about the dissolving of potassium nitrate at this lower temperature? <code>[1]</code></p>
<p><code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\mathrm{KNO_3(s) \rightarrow K^{+}(aq) + NO_3^{-}(aq)}\)</span> (or with <span class="math inline">\(+ aq\)</span> on the left). <code>[1]</code></li>
<li><strong>(b)</strong> Increase in disorder because a solid becomes an aqueous solution / the number of particles per mole of solution increases. <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(\Delta G^\ominus = \Delta H^\ominus - T\Delta S^\ominus = 0\)</span>, so <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S} = \dfrac{34.9}{(117/1000)}\)</span> <code>[1+1]</code> <span class="math inline">\(= 298\ \mathrm{K}\)</span>. <code>[1]</code></li>
<li><strong>(d)(i)</strong> <span class="math inline">\(\Delta G^\ominus\)</span> becomes positive / increases (<span class="math inline">\(\Delta G^\ominus &gt; 0\)</span>). <code>[1]</code></li>
<li><strong>(d)(ii)</strong> Dissolving is no longer spontaneous / no longer feasible / potassium nitrate does not dissolve (or dissolves less). <code>[1]</code></li>
</ul>
</details>
</section>
<div class="small-note">
<p><strong>Source check:</strong> the model answer in the original PDF mistakenly writes KBr; the correct salt in the question is potassium nitrate, <span class="math inline">\(\mathrm{KNO_3}\)</span>.</p>
</div>
<section id="example-19-combustion-of-ethanol-5.2-sq-medium-q4" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-19-combustion-of-ethanol-5.2-sq-medium-q4">Example 19 · Combustion of ethanol · 5.2 SQ Medium Q4</h3>
<p>Ethanol is used in large quantities in the production of alcoholic beverages and as a fuel.</p>
<p>The combustion of ethanol is represented by the equation:</p>
<p><span class="math display">\[\mathrm{CH_3CH_2OH(l) + 3O_2(g) \rightarrow 2CO_2(g) + 3H_2O(g)} \qquad \Delta H^\ominus = -1367\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p><strong>(a)</strong> Using Table 4.1, determine the entropy change, <span class="math inline">\(\Delta S^\ominus\)</span>, for the combustion of ethanol at 298 K. Show your working.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Substance</th>
<th style="text-align: right;">CH₃CH₂OH(l)</th>
<th style="text-align: right;">3O₂(g)</th>
<th style="text-align: right;">2CO₂(g)</th>
<th style="text-align: right;">3H₂O(g)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(S^\ominus\)</span> / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></td>
<td style="text-align: right;">+161</td>
<td style="text-align: right;">+205.2</td>
<td style="text-align: right;">+213.8</td>
<td style="text-align: right;">+188.8</td>
</tr>
</tbody>
</table>
<p><code>[3 marks]</code></p>
<p><strong>(b)</strong> Calculate the free energy change, <span class="math inline">\(\Delta G^\ominus\)</span>, for the combustion of ethanol using <span class="math inline">\(\Delta S^\ominus\)</span> determined in part (a). <code>[3 marks]</code></p>
<p><strong>(c)</strong> Explain whether changing the temperature for the combustion of ethanol will alter the spontaneity of the reaction. <code>[3 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\Delta S^\ominus = [(2 \times 213.8) + (3 \times 188.8)] - [(1 \times 161) + (3 \times 205.2)]\)</span> <code>[1]</code> <span class="math inline">\(= 994 - 776.6\)</span> <code>[1]</code> <span class="math inline">\(= +217.4\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(b)</strong> <span class="math inline">\(\Delta G^\ominus = \Delta H^\ominus - T\Delta S^\ominus\)</span> <code>[1]</code> <span class="math inline">\(= -1367 - (298 \times 0.2174)\)</span> <code>[1]</code> <span class="math inline">\(= -1432\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(c)</strong> Changing the temperature does not alter the spontaneity <code>[1]</code>; <span class="math inline">\(\Delta H^\ominus\)</span> for this reaction is always negative and <span class="math inline">\(\Delta S^\ominus\)</span> is always positive <code>[1]</code>; so <span class="math inline">\(\Delta G^\ominus\)</span> is always negative at any temperature. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="entropy---hard" class="level3">
<h3 class="anchored" data-anchor-id="entropy---hard">5.2 Entropy - Hard</h3>
</section>
<section id="example-20-methanol-synthesis-at-790-k-5.2-sq-hard-q1" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-20-methanol-synthesis-at-790-k-5.2-sq-hard-q1">Example 20 · Methanol synthesis at 790 K · 5.2 SQ Hard Q1</h3>
<p>Carbon dioxide and hydrogen can react to form methanol.</p>
<p><span class="math display">\[\mathrm{CO_2(g) + 3H_2(g) \rightleftharpoons CH_3OH(g) + H_2O(g)}\]</span></p>
<p>Data for enthalpy of formation and entropy is shown in Table 1.1.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">CO₂(g)</th>
<th style="text-align: right;">H₂(g)</th>
<th style="text-align: right;">CH₃OH(g)</th>
<th style="text-align: right;">H₂O(g)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_f\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></td>
<td style="text-align: right;">−394</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">−201</td>
<td style="text-align: right;">−242</td>
</tr>
<tr class="even">
<td><span class="math inline">\(S^\ominus\)</span> / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">238</td>
<td style="text-align: right;">189</td>
</tr>
</tbody>
</table>
<p><strong>(a)</strong> Calculate the Gibbs free-energy change, <span class="math inline">\(\Delta G\)</span>, in <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span>, for this reaction at 790 K. <code>[4 marks]</code></p>
<p><strong>(b)</strong> Explain whether this reaction is feasible at 790 K. <code>[1 mark]</code></p>
<p><strong>(c)</strong> Use your values of <span class="math inline">\(\Delta H\)</span> and <span class="math inline">\(\Delta S\)</span> from part (a) to calculate the temperature above which this reaction is feasible. <code>[3 marks]</code></p>
<p><strong>(d)</strong> Explain why the reaction in part (a) has a negative entropy change. <code>[1 mark]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> <span class="math inline">\(\Delta H^\ominus = (-201 + -242) - (-394) = -49\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta S^\ominus = (238 + 189) - (3 \times 131 + 214) = -180\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta G = -49 - (790 \times -0.180)\)</span> <code>[1]</code> <span class="math inline">\(= +93.2\ \mathrm{kJ\,mol^{-1}}\)</span>. <code>[1]</code></li>
<li><strong>(b)</strong> Not feasible, as <span class="math inline">\(\Delta G\)</span> is positive / more than zero. <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S} = \dfrac{-49}{-0.180}\)</span> <code>[1+1]</code> <span class="math inline">\(= 272\ \mathrm{K}\)</span>; the reaction is feasible at <span class="math inline">\(T &lt; 272\ \mathrm{K}\)</span>. <code>[1]</code></li>
<li><strong>(d)</strong> Fewer molecules / moles of gas are formed in the reaction (4 mol gas → 2 mol gas), so the system becomes less disordered. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-21-calcium-carbonate-stability-and-the-temperature-limits-of-feasibility-5.2-sq-hard-q2" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-21-calcium-carbonate-stability-and-the-temperature-limits-of-feasibility-5.2-sq-hard-q2">Example 21 · Calcium carbonate stability and the temperature limits of feasibility · 5.2 SQ Hard Q2</h3>
<p>This question is about the feasibility of a reaction.</p>
<p>Calcium carbonate can be thermally decomposed to make calcium oxide.</p>
<p><span class="math display">\[\mathrm{CaCO_3(s) \rightarrow CaO(s) + CO_2(g)} \qquad \Delta H = +178\ \mathrm{kJ\,mol^{-1}}\]</span></p>
<p>Table 2.1 shows the standard entropies of each substance.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Substance</th>
<th style="text-align: right;">CaCO₃(s)</th>
<th style="text-align: right;">CaO(s)</th>
<th style="text-align: right;">CO₂(g)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(S^\ominus\)</span> / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">214</td>
</tr>
</tbody>
</table>
<p><strong>(a)</strong></p>
<p><strong>(i)</strong> Use the information in Table 2.1 to show that calcium carbonate is stable at room temperature (25 °C). <code>[4]</code></p>
<p><strong>(ii)</strong> Calculate the minimum temperature needed to decompose calcium carbonate. <code>[2]</code></p>
<p><code>[6 marks]</code></p>
<p><strong>(b)</strong> Explain how the conditions can be changed for the reaction in (a) to make the reaction feasible. <code>[3 marks]</code></p>
<p><strong>(c)</strong> The evaporation of water is an endothermic reaction but also a spontaneous reaction.</p>
<p>Explain why. Refer to the entropy change that occurs and the change in the arrangement of water molecules. <code>[4 marks]</code></p>
<p><strong>(d)</strong> Use the information in Table 2.2 to calculate the temperature above which the reaction between hydrogen and oxygen to form gaseous water is not feasible.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(S^\ominus\)</span> / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\Delta H^\ominus_f\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H₂(g)</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>O₂(g)</td>
<td style="text-align: right;">205</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>H₂O(g)</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">−242</td>
</tr>
</tbody>
</table>
<p><code>[4 marks]</code></p>
<p><strong>(e)</strong> Explain what would happen to the sample of gaseous water if it was heated to a higher temperature than that calculated in part (d). <code>[2 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)(i)</strong> <span class="math inline">\(\Delta S^\ominus = 40 + 214 - 89 = +165\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta G^\ominus = 178 - (298 \times 0.165)\)</span> <code>[1]</code> <span class="math inline">\(= +129\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta G^\ominus\)</span> is positive, so the reaction is not feasible and CaCO₃ is stable. <code>[1]</code></li>
<li><strong>(a)(ii)</strong> <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S} = \dfrac{178}{0.165}\)</span> <code>[1]</code> <span class="math inline">\(= 1079\ \mathrm{K}\)</span> (806 °C). <code>[1]</code></li>
<li><strong>(b)</strong> Increase the temperature <code>[1]</code>; so that <span class="math inline">\(T\Delta S &gt; \Delta H\)</span> <code>[1]</code>; and <span class="math inline">\(\Delta G &lt; 0\)</span>. <code>[1]</code></li>
<li><strong>(c)</strong> The molecules become more disordered when evaporation occurs <code>[1]</code>; the entropy change is positive <code>[1]</code>; <span class="math inline">\(T\Delta S &gt; \Delta H\)</span> <code>[1]</code>; (so) <span class="math inline">\(\Delta G &lt; 0\)</span> and the process is spontaneous. <code>[1]</code></li>
<li><strong>(d)</strong> <span class="math inline">\(\Delta S^\ominus = 189 - (131 + \tfrac{1}{2} \times 205) = -44.5\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S}\)</span> <code>[1]</code> <span class="math inline">\(= \dfrac{-242 \times 1000}{-44.5}\)</span> <code>[1]</code> <span class="math inline">\(= 5438\ \mathrm{K}\)</span> (5165 °C; 5400–5500 K accepted). <code>[1]</code></li>
<li><strong>(e)</strong> The water would decompose into hydrogen and oxygen <code>[1]</code>; because <span class="math inline">\(\Delta G\)</span> for the decomposition is less than zero / the reverse reaction is feasible. <code>[1]</code></li>
</ul>
</details>
</section>
<section id="example-22-predicting-signs-of-delta-s-and-the-temperature-for-so₂-oxidation-5.2-sq-hard-q3" class="level3 question-card">
<h3 class="anchored" data-anchor-id="example-22-predicting-signs-of-delta-s-and-the-temperature-for-so₂-oxidation-5.2-sq-hard-q3">Example 22 · Predicting signs of <span class="math inline">\(\Delta S\)</span> and the temperature for SO₂ oxidation · 5.2 SQ Hard Q3</h3>
<p>Free energy changes can be used to predict the feasibility of chemical reactions and processes.</p>
<p><strong>(a)</strong> Table 3.1 shows the equations of five different chemical reactions or processes.</p>
<p>Complete the table by predicting the sign of <span class="math inline">\(\Delta S\)</span> for each chemical reaction and process.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Chemical reaction or process</th>
<th>Sign of <span class="math inline">\(\Delta S\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathrm{MgCl_2(s) + aq \rightarrow MgCl_2(aq)}\)</span></td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{Ca(s) + H_2SO_4(aq) \rightarrow CaSO_4(aq) + H_2(g)}\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{Na_2SO_4(s) + 10H_2O(l) \rightarrow Na_2SO_4\cdot10H_2O(s)}\)</span></td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{2CO(g) + O_2(g) \rightarrow 2CO_2(g)}\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{C_2H_5OH(g) \rightarrow C_2H_5OH(l)}\)</span></td>
<td></td>
</tr>
</tbody>
</table>
<p><code>[2 marks]</code></p>
<p><strong>(b)</strong> The enthalpy and entropy changes of a reaction are both negative.</p>
<p>Explain how the feasibility of this reaction will change as the temperature decreases. <code>[2 marks]</code></p>
<p><strong>(c)</strong> The equation of a reversible reaction is shown below:</p>
<p><span class="math display">\[\mathrm{2SO_2(g) + O_2(g) \rightleftharpoons 2SO_3(g)}\]</span></p>
<p>Use the information in Table 3.2 to determine the temperature at which the reaction becomes feasible. Show your working.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">SO₂</th>
<th style="text-align: right;">O₂</th>
<th style="text-align: right;">SO₃</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\Delta H^\ominus_f\)</span> / <span class="math inline">\(\mathrm{kJ\,mol^{-1}}\)</span></td>
<td style="text-align: right;">−296.8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">−395.7</td>
</tr>
<tr class="even">
<td><span class="math inline">\(S^\ominus\)</span> / <span class="math inline">\(\mathrm{J\,K^{-1}\,mol^{-1}}\)</span></td>
<td style="text-align: right;">248.2</td>
<td style="text-align: right;">205.1</td>
<td style="text-align: right;">256.8</td>
</tr>
</tbody>
</table>
<p><code>[6 marks]</code></p>
<details class="answer-panel">
<summary>
Show mark scheme / model answer
</summary>
<ul>
<li><strong>(a)</strong> Signs in order: +, +, −, −, − <code>[2 marks for all five correct; 1 mark for three or four correct]</code>.</li>
<li><strong>(b)</strong> As the temperature decreases, <span class="math inline">\(\Delta G\)</span> decreases and the reaction is more feasible <code>[1]</code>; because <span class="math inline">\(T\Delta S\)</span> decreases in magnitude / becomes less negative. <code>[1]</code></li>
<li><strong>(c)</strong> <span class="math inline">\(\Delta H^\ominus = (2 \times -395.7) - (2 \times -296.8 + 0) = -197.8\ \mathrm{kJ\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(\Delta S^\ominus = (2 \times 256.8) - (2 \times 248.2 + 205.1) = -187.9\ \mathrm{J\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; convert: <span class="math inline">\(\Delta S^\ominus = -0.1879\ \mathrm{kJ\,K^{-1}\,mol^{-1}}\)</span> <code>[1]</code>; <span class="math inline">\(T = \dfrac{\Delta H}{\Delta S} = \dfrac{197.8}{0.1879}\)</span> <code>[1+1]</code> <span class="math inline">\(= 1053\ \mathrm{K}\)</span>. <code>[1]</code></li>
</ul>
</details>
</section>
</section>
<section id="chapter-checklist" class="level2">
<h2 class="anchored" data-anchor-id="chapter-checklist">Chapter checklist</h2>
<ul class="task-list">
<li><label><input type="checkbox">我能准确说出 lattice energy、enthalpy of atomisation、electron affinity、enthalpy of solution、enthalpy of hydration 的定义。</label></li>
<li><label><input type="checkbox">我能画出并补全 Born–Haber cycle，识别每一步的焓变。</label></li>
<li><label><input type="checkbox">我能用 Born–Haber cycle 计算晶格能（注意计量数倍率）。</label></li>
<li><label><input type="checkbox">我能用离子电荷与离子半径解释晶格能和水合焓的大小比较。</label></li>
<li><label><input type="checkbox">我能判断一个过程的熵增/熵减，并计算 <span class="math inline">\(\Delta S^\ominus\)</span>。</label></li>
<li><label><input type="checkbox">我能用 <span class="math inline">\(\Delta G^\ominus=\Delta H^\ominus-T\Delta S^\ominus\)</span> 判断可行性并换算单位。</label></li>
<li><label><input type="checkbox">我能说明温度对四种 <span class="math inline">\(\Delta H^\ominus / \Delta S^\ominus\)</span> 组合下可行性的影响。</label></li>
</ul>
<section id="original-question-pdfs" class="level3">
<h3 class="anchored" data-anchor-id="original-question-pdfs">Original question PDFs</h3>
<ul>
<li><a href="https://raw.githubusercontent.com/nanoxsj/CIE-Chemistry-Study/main/resources/original-papers/chemical-energetics/23.1-lattice-energy-born-haber-easy.pdf">23.1 Lattice Energy and Born–Haber Cycles – Easy</a></li>
<li><a href="https://raw.githubusercontent.com/nanoxsj/CIE-Chemistry-Study/main/resources/original-papers/chemical-energetics/23.1-lattice-energy-born-haber-medium.pdf">23.1 Lattice Energy and Born–Haber Cycles – Medium</a></li>
<li><a href="https://raw.githubusercontent.com/nanoxsj/CIE-Chemistry-Study/main/resources/original-papers/chemical-energetics/23.1-lattice-energy-born-haber-hard.pdf">23.1 Lattice Energy and Born–Haber Cycles – Hard</a></li>
<li><a href="https://raw.githubusercontent.com/nanoxsj/CIE-Chemistry-Study/main/resources/original-papers/chemical-energetics/23.2-entropy-easy.pdf">23.2 Entropy – Easy</a></li>
<li><a href="https://raw.githubusercontent.com/nanoxsj/CIE-Chemistry-Study/main/resources/original-papers/chemical-energetics/23.2-entropy-medium.pdf">23.2 Entropy – Medium</a></li>
<li><a href="https://raw.githubusercontent.com/nanoxsj/CIE-Chemistry-Study/main/resources/original-papers/chemical-energetics/23.2-entropy-hard.pdf">23.2 Entropy – Hard</a></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script>
document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll(".done-toggle input").forEach((input) => {
    const key = `cie-chem-${input.dataset.progress}`;
    input.checked = localStorage.getItem(key) === "true";
    input.closest(".question-card")?.classList.toggle("is-complete", input.checked);
    input.addEventListener("change", () => {
      localStorage.setItem(key, input.checked);
      input.closest(".question-card")?.classList.toggle("is-complete", input.checked);
    });
  });

  document.querySelectorAll(".mc-question").forEach((card) => {
    const answer = card.dataset.answer;
    const feedback = card.querySelector(".mc-feedback");
    const check = card.querySelector(".check-answer");
    let selected = localStorage.getItem(`cie-chem-${card.id}-choice`) || "";

    const showSelection = () => {
      card.querySelectorAll(".mc-choice").forEach((choice) => {
        choice.classList.toggle("is-selected", choice.dataset.choice === selected);
      });
    };
    showSelection();

    card.querySelectorAll(".mc-choice").forEach((choice) => {
      choice.addEventListener("click", () => {
        selected = choice.dataset.choice;
        localStorage.setItem(`cie-chem-${card.id}-choice`, selected);
        feedback.textContent = "";
        feedback.className = "mc-feedback";
        showSelection();
      });
    });

    check?.addEventListener("click", () => {
      if (!selected) {
        feedback.textContent = "Select an answer first.";
        feedback.className = "mc-feedback is-pending";
        return;
      }
      const correct = selected === answer;
      feedback.textContent = correct ? "Correct." : `Not quite. The correct answer is ${answer}.`;
      feedback.className = `mc-feedback ${correct ? "is-correct" : "is-incorrect"}`;
    });
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已复制");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已复制");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/nanoxsj\.github\.io\/CIE-Chemistry-Study\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../a-level/13-introduction-to-as-organic-chemistry.html" class="pagination-link" aria-label="13 An introduction to AS Level organic chemistry">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">13 An introduction to AS Level organic chemistry</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../a-level/24-electrochemistry.html" class="pagination-link" aria-label="24 Electrochemistry">
        <span class="nav-page-text">24 Electrochemistry</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>